<?php

/**
 * Trajet form base class.
 *
 * @method Trajet getObject() Returns the current form's model object
 *
 * @package    roulezmailn_v3
 * @subpackage form
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseTrajetForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_trajet'                     => new sfWidgetFormInputHidden(),
      'bascule'                       => new sfWidgetFormInputText(),
      'cle'                           => new sfWidgetFormInputText(),
      'etat'                          => new sfWidgetFormInputText(),
      'actif'                         => new sfWidgetFormInputText(),
      'etat_avant_bascule'            => new sfWidgetFormInputText(),
      'site_confidentiel'             => new sfWidgetFormInputText(),
      'id_utilisateur'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Covoitureur'), 'add_empty' => true)),
      'id_partenaire'                 => new sfWidgetFormInputText(),
      'id_offre_sur_site_partenaire'  => new sfWidgetFormInputText(),
      'id_site'                       => new sfWidgetFormInputText(),
      'id_site_site'                  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('SiteClient'), 'add_empty' => false)),
      'id_type_trajet'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('TrajetTypeCovoiturage'), 'add_empty' => false)),
      'id_nature_trajet'              => new sfWidgetFormInputText(),
      'id_frequence'                  => new sfWidgetFormInputText(),
      'id_depart'                     => new sfWidgetFormInputText(),
      'id_depart2'                    => new sfWidgetFormInputText(),
      'id_depart_pays'                => new sfWidgetFormInputText(),
      'depart_insee'                  => new sfWidgetFormInputText(),
      'depart_libelle'                => new sfWidgetFormInputText(),
      'depart_adresse'                => new sfWidgetFormInputText(),
      'depart_adresse_numero'         => new sfWidgetFormInputText(),
      'depart_code_postal'            => new sfWidgetFormInputText(),
      'depart_ville'                  => new sfWidgetFormInputText(),
      'depart_pays'                   => new sfWidgetFormInputText(),
      'depart_latitude'               => new sfWidgetFormInputText(),
      'depart_longitude'              => new sfWidgetFormInputText(),
      'depart_type'                   => new sfWidgetFormInputText(),
      'depart_autre_lieu'             => new sfWidgetFormInputText(),
      'id_destination'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('VilleFr'), 'add_empty' => false)),
      'id_destination2'               => new sfWidgetFormInputText(),
      'id_destination_pays'           => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('PaysMonde'), 'add_empty' => false)),
      'destination_insee'             => new sfWidgetFormInputText(),
      'destination_libelle'           => new sfWidgetFormInputText(),
      'destination_adresse'           => new sfWidgetFormInputText(),
      'destination_adresse_numero'    => new sfWidgetFormInputText(),
      'destination_code_postal'       => new sfWidgetFormInputText(),
      'destination_ville'             => new sfWidgetFormInputText(),
      'destination_pays'              => new sfWidgetFormInputText(),
      'destination_latitude'          => new sfWidgetFormInputText(),
      'destination_longitude'         => new sfWidgetFormInputText(),
      'destination_type'              => new sfWidgetFormInputText(),
      'destination_autre_lieu'        => new sfWidgetFormInputText(),
      'etape1_ville'                  => new sfWidgetFormInputText(),
      'etape1_insee'                  => new sfWidgetFormInputText(),
      'etape_departement1'            => new sfWidgetFormInputText(),
      'etape1_lieu_id'                => new sfWidgetFormInputText(),
      'etape2_ville'                  => new sfWidgetFormInputText(),
      'etape2_insee'                  => new sfWidgetFormInputText(),
      'etape_departement2'            => new sfWidgetFormInputText(),
      'etape2_lieu_id'                => new sfWidgetFormInputText(),
      'etape3_ville'                  => new sfWidgetFormInputText(),
      'etape3_insee'                  => new sfWidgetFormInputText(),
      'etape_departement3'            => new sfWidgetFormInputText(),
      'etape3_lieu_id'                => new sfWidgetFormInputText(),
      'etape4_ville'                  => new sfWidgetFormInputText(),
      'etape4_insee'                  => new sfWidgetFormInputText(),
      'etape_departement4'            => new sfWidgetFormInputText(),
      'etape4_lieu_id'                => new sfWidgetFormInputText(),
      'etape5_ville'                  => new sfWidgetFormInputText(),
      'etape5_insee'                  => new sfWidgetFormInputText(),
      'etape_departement5'            => new sfWidgetFormInputText(),
      'etape5_lieu_id'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Lieu'), 'add_empty' => true)),
      'trajet_organisme'              => new sfWidgetFormInputText(),
      'km'                            => new sfWidgetFormInputText(),
      'id_zone_entreprise'            => new sfWidgetFormInputText(),
      'id_evenement'                  => new sfWidgetFormInputText(),
      'zone_entreprise_autre'         => new sfWidgetFormInputText(),
      'jour_unique_type_cov'          => new sfWidgetFormInputText(),
      'jour_unique_date'              => new sfWidgetFormDateTime(),
      'jour_unique_heure'             => new sfWidgetFormTime(),
      'jour_unique_type_cov_retour'   => new sfWidgetFormInputText(),
      'jour_unique_date_retour'       => new sfWidgetFormDate(),
      'jour_unique_heure_retour'      => new sfWidgetFormTime(),
      'jour_unique_retour'            => new sfWidgetFormInputText(),
      'jour_unique_description'       => new sfWidgetFormInputText(),
      'lundi_type_cov'                => new sfWidgetFormInputText(),
      'lundi_etat'                    => new sfWidgetFormInputText(),
      'lundi_heure_depart'            => new sfWidgetFormTime(),
      'lundi_heure_retour'            => new sfWidgetFormTime(),
      'mardi_type_cov'                => new sfWidgetFormInputText(),
      'mardi_etat'                    => new sfWidgetFormInputText(),
      'mardi_heure_depart'            => new sfWidgetFormTime(),
      'mardi_heure_retour'            => new sfWidgetFormTime(),
      'mercredi_type_cov'             => new sfWidgetFormInputText(),
      'mercredi_etat'                 => new sfWidgetFormInputText(),
      'mercredi_heure_depart'         => new sfWidgetFormTime(),
      'mercredi_heure_retour'         => new sfWidgetFormTime(),
      'jeudi_type_cov'                => new sfWidgetFormInputText(),
      'jeudi_etat'                    => new sfWidgetFormInputText(),
      'jeudi_heure_depart'            => new sfWidgetFormTime(),
      'jeudi_heure_retour'            => new sfWidgetFormTime(),
      'vendredi_type_cov'             => new sfWidgetFormInputText(),
      'vendredi_etat'                 => new sfWidgetFormInputText(),
      'vendredi_heure_depart'         => new sfWidgetFormTime(),
      'vendredi_heure_retour'         => new sfWidgetFormTime(),
      'samedi_type_cov'               => new sfWidgetFormInputText(),
      'samedi_etat'                   => new sfWidgetFormInputText(),
      'samedi_heure_depart'           => new sfWidgetFormTime(),
      'samedi_heure_retour'           => new sfWidgetFormTime(),
      'dimanche_type_cov'             => new sfWidgetFormInputText(),
      'dimanche_etat'                 => new sfWidgetFormInputText(),
      'dimanche_heure_depart'         => new sfWidgetFormTime(),
      'dimanche_heure_retour'         => new sfWidgetFormTime(),
      'date_creation'                 => new sfWidgetFormDateTime(),
      'date_depublication'            => new sfWidgetFormDate(),
      'date_modification'             => new sfWidgetFormDateTime(),
      'date_verification'             => new sfWidgetFormDateTime(),
      'nombre_de_place'               => new sfWidgetFormInputText(),
      'mobilite_r'                    => new sfWidgetFormInputText(),
      'description'                   => new sfWidgetFormTextarea(),
      'trajet_etudiant'               => new sfWidgetFormInputText(),
      'nombre_visualisation'          => new sfWidgetFormInputText(),
      'nombre_demande'                => new sfWidgetFormInputText(),
      'cout'                          => new sfWidgetFormInputText(),
      'cout_passager'                 => new sfWidgetFormInputText(),
      'autoroute'                     => new sfWidgetFormInputText(),
      'autoroute_cout'                => new sfWidgetFormInputText(),
      'autoroute_text'                => new sfWidgetFormInputText(),
      'vehicule'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CovoitureurVehicule'), 'add_empty' => true)),
      'tolerance'                     => new sfWidgetFormInputText(),
      'url_retour'                    => new sfWidgetFormInputText(),
      'technique'                     => new sfWidgetFormTextarea(),
      'visible_uniquement_partenaire' => new sfWidgetFormInputText(),
      'id_type_vehicule'              => new sfWidgetFormInputText(),
      'volume_bagage'                 => new sfWidgetFormInputText(),
      'covoiturage_solidaire'         => new sfWidgetFormInputText(),
      'id_equipage'                   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Equipage'), 'add_empty' => true)),
      'cp_trajet_id'                  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpTrajet'), 'add_empty' => true)),
      'presence_vehicule'             => new sfWidgetFormInputText(),
      'cp_type_action_statut_id'      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpTypeActionStatut'), 'add_empty' => true)),
    ));

    $this->setValidators(array(
      'id_trajet'                     => new sfValidatorChoice(array('choices' => array($this->getObject()->get('id_trajet')), 'empty_value' => $this->getObject()->get('id_trajet'), 'required' => false)),
      'bascule'                       => new sfValidatorInteger(array('required' => false)),
      'cle'                           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'etat'                          => new sfValidatorInteger(array('required' => false)),
      'actif'                         => new sfValidatorInteger(array('required' => false)),
      'etat_avant_bascule'            => new sfValidatorInteger(array('required' => false)),
      'site_confidentiel'             => new sfValidatorInteger(array('required' => false)),
      'id_utilisateur'                => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Covoitureur'), 'required' => false)),
      'id_partenaire'                 => new sfValidatorInteger(array('required' => false)),
      'id_offre_sur_site_partenaire'  => new sfValidatorInteger(array('required' => false)),
      'id_site'                       => new sfValidatorInteger(array('required' => false)),
      'id_site_site'                  => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('SiteClient'), 'required' => false)),
      'id_type_trajet'                => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('TrajetTypeCovoiturage'), 'required' => false)),
      'id_nature_trajet'              => new sfValidatorInteger(array('required' => false)),
      'id_frequence'                  => new sfValidatorInteger(array('required' => false)),
      'id_depart'                     => new sfValidatorInteger(array('required' => false)),
      'id_depart2'                    => new sfValidatorInteger(array('required' => false)),
      'id_depart_pays'                => new sfValidatorInteger(array('required' => false)),
      'depart_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'depart_libelle'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'depart_adresse'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'depart_adresse_numero'         => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'depart_code_postal'            => new sfValidatorInteger(array('required' => false)),
      'depart_ville'                  => new sfValidatorString(array('max_length' => 255)),
      'depart_pays'                   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'depart_latitude'               => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'depart_longitude'              => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'depart_type'                   => new sfValidatorInteger(array('required' => false)),
      'depart_autre_lieu'             => new sfValidatorInteger(array('required' => false)),
      'id_destination'                => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('VilleFr'), 'required' => false)),
      'id_destination2'               => new sfValidatorInteger(array('required' => false)),
      'id_destination_pays'           => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('PaysMonde'), 'required' => false)),
      'destination_insee'             => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'destination_libelle'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'destination_adresse'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'destination_adresse_numero'    => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'destination_code_postal'       => new sfValidatorInteger(array('required' => false)),
      'destination_ville'             => new sfValidatorString(array('max_length' => 255)),
      'destination_pays'              => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'destination_latitude'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'destination_longitude'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'destination_type'              => new sfValidatorInteger(array('required' => false)),
      'destination_autre_lieu'        => new sfValidatorInteger(array('required' => false)),
      'etape1_ville'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'etape1_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'etape_departement1'            => new sfValidatorInteger(array('required' => false)),
      'etape1_lieu_id'                => new sfValidatorInteger(array('required' => false)),
      'etape2_ville'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'etape2_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'etape_departement2'            => new sfValidatorInteger(array('required' => false)),
      'etape2_lieu_id'                => new sfValidatorInteger(array('required' => false)),
      'etape3_ville'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'etape3_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'etape_departement3'            => new sfValidatorInteger(array('required' => false)),
      'etape3_lieu_id'                => new sfValidatorInteger(array('required' => false)),
      'etape4_ville'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'etape4_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'etape_departement4'            => new sfValidatorInteger(array('required' => false)),
      'etape4_lieu_id'                => new sfValidatorInteger(array('required' => false)),
      'etape5_ville'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'etape5_insee'                  => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'etape_departement5'            => new sfValidatorInteger(array('required' => false)),
      'etape5_lieu_id'                => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Lieu'), 'required' => false)),
      'trajet_organisme'              => new sfValidatorInteger(array('required' => false)),
      'km'                            => new sfValidatorString(array('max_length' => 100)),
      'id_zone_entreprise'            => new sfValidatorInteger(array('required' => false)),
      'id_evenement'                  => new sfValidatorInteger(array('required' => false)),
      'zone_entreprise_autre'         => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'jour_unique_type_cov'          => new sfValidatorInteger(array('required' => false)),
      'jour_unique_date'              => new sfValidatorDateTime(array('required' => false)),
      'jour_unique_heure'             => new sfValidatorTime(array('required' => false)),
      'jour_unique_type_cov_retour'   => new sfValidatorInteger(array('required' => false)),
      'jour_unique_date_retour'       => new sfValidatorDate(array('required' => false)),
      'jour_unique_heure_retour'      => new sfValidatorTime(array('required' => false)),
      'jour_unique_retour'            => new sfValidatorInteger(array('required' => false)),
      'jour_unique_description'       => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'lundi_type_cov'                => new sfValidatorInteger(array('required' => false)),
      'lundi_etat'                    => new sfValidatorInteger(array('required' => false)),
      'lundi_heure_depart'            => new sfValidatorTime(array('required' => false)),
      'lundi_heure_retour'            => new sfValidatorTime(array('required' => false)),
      'mardi_type_cov'                => new sfValidatorInteger(array('required' => false)),
      'mardi_etat'                    => new sfValidatorInteger(array('required' => false)),
      'mardi_heure_depart'            => new sfValidatorTime(array('required' => false)),
      'mardi_heure_retour'            => new sfValidatorTime(array('required' => false)),
      'mercredi_type_cov'             => new sfValidatorInteger(array('required' => false)),
      'mercredi_etat'                 => new sfValidatorInteger(array('required' => false)),
      'mercredi_heure_depart'         => new sfValidatorTime(array('required' => false)),
      'mercredi_heure_retour'         => new sfValidatorTime(array('required' => false)),
      'jeudi_type_cov'                => new sfValidatorInteger(array('required' => false)),
      'jeudi_etat'                    => new sfValidatorInteger(array('required' => false)),
      'jeudi_heure_depart'            => new sfValidatorTime(array('required' => false)),
      'jeudi_heure_retour'            => new sfValidatorTime(array('required' => false)),
      'vendredi_type_cov'             => new sfValidatorInteger(array('required' => false)),
      'vendredi_etat'                 => new sfValidatorInteger(array('required' => false)),
      'vendredi_heure_depart'         => new sfValidatorTime(array('required' => false)),
      'vendredi_heure_retour'         => new sfValidatorTime(array('required' => false)),
      'samedi_type_cov'               => new sfValidatorInteger(array('required' => false)),
      'samedi_etat'                   => new sfValidatorInteger(array('required' => false)),
      'samedi_heure_depart'           => new sfValidatorTime(array('required' => false)),
      'samedi_heure_retour'           => new sfValidatorTime(array('required' => false)),
      'dimanche_type_cov'             => new sfValidatorInteger(array('required' => false)),
      'dimanche_etat'                 => new sfValidatorInteger(array('required' => false)),
      'dimanche_heure_depart'         => new sfValidatorTime(array('required' => false)),
      'dimanche_heure_retour'         => new sfValidatorTime(array('required' => false)),
      'date_creation'                 => new sfValidatorDateTime(array('required' => false)),
      'date_depublication'            => new sfValidatorDate(array('required' => false)),
      'date_modification'             => new sfValidatorDateTime(array('required' => false)),
      'date_verification'             => new sfValidatorDateTime(array('required' => false)),
      'nombre_de_place'               => new sfValidatorInteger(array('required' => false)),
      'mobilite_r'                    => new sfValidatorInteger(array('required' => false)),
      'description'                   => new sfValidatorString(array('required' => false)),
      'trajet_etudiant'               => new sfValidatorInteger(array('required' => false)),
      'nombre_visualisation'          => new sfValidatorInteger(array('required' => false)),
      'nombre_demande'                => new sfValidatorInteger(array('required' => false)),
      'cout'                          => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'cout_passager'                 => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'autoroute'                     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'autoroute_cout'                => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'autoroute_text'                => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'vehicule'                      => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('CovoitureurVehicule'), 'required' => false)),
      'tolerance'                     => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'url_retour'                    => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'technique'                     => new sfValidatorString(array('required' => false)),
      'visible_uniquement_partenaire' => new sfValidatorInteger(array('required' => false)),
      'id_type_vehicule'              => new sfValidatorInteger(),
      'volume_bagage'                 => new sfValidatorInteger(array('required' => false)),
      'covoiturage_solidaire'         => new sfValidatorInteger(array('required' => false)),
      'id_equipage'                   => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Equipage'), 'required' => false)),
      'cp_trajet_id'                  => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('CpTrajet'), 'required' => false)),
      'presence_vehicule'             => new sfValidatorInteger(array('required' => false)),
      'cp_type_action_statut_id'      => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('CpTypeActionStatut'), 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('trajet[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Trajet';
  }

}
