<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContenuRubrique', 'dbrmv3');

/**
 * BaseContenuRubrique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_rubrique
 * @property integer $id_site
 * @property integer $etat
 * @property integer $nombre_affichage
 * @property integer $id_rubrique_mere
 * @property string $fr_titre
 * @property string $nom_repertoire_fr
 * @property string $en_titre
 * @property integer $id_administrateur
 * @property integer $priorite
 * @property timestamp $date_creation
 * @property timestamp $date_modification
 * @property string $lien_url
 * @property integer $id_perm
 * @property ContenuRubrique $ContenuRubrique
 * @property sfGuardUser $sfGuardUser
 * @property sfGuardPermission $sfGuardPermission
 * @property Doctrine_Collection $Contenu
 * 
 * @method integer             getIdRubrique()        Returns the current record's "id_rubrique" value
 * @method integer             getIdSite()            Returns the current record's "id_site" value
 * @method integer             getEtat()              Returns the current record's "etat" value
 * @method integer             getNombreAffichage()   Returns the current record's "nombre_affichage" value
 * @method integer             getIdRubriqueMere()    Returns the current record's "id_rubrique_mere" value
 * @method string              getFrTitre()           Returns the current record's "fr_titre" value
 * @method string              getNomRepertoireFr()   Returns the current record's "nom_repertoire_fr" value
 * @method string              getEnTitre()           Returns the current record's "en_titre" value
 * @method integer             getIdAdministrateur()  Returns the current record's "id_administrateur" value
 * @method integer             getPriorite()          Returns the current record's "priorite" value
 * @method timestamp           getDateCreation()      Returns the current record's "date_creation" value
 * @method timestamp           getDateModification()  Returns the current record's "date_modification" value
 * @method string              getLienUrl()           Returns the current record's "lien_url" value
 * @method integer             getIdPerm()            Returns the current record's "id_perm" value
 * @method ContenuRubrique     getContenuRubrique()   Returns the current record's "ContenuRubrique" value
 * @method sfGuardUser         getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method sfGuardPermission   getSfGuardPermission() Returns the current record's "sfGuardPermission" value
 * @method Doctrine_Collection getContenu()           Returns the current record's "Contenu" collection
 * @method ContenuRubrique     setIdRubrique()        Sets the current record's "id_rubrique" value
 * @method ContenuRubrique     setIdSite()            Sets the current record's "id_site" value
 * @method ContenuRubrique     setEtat()              Sets the current record's "etat" value
 * @method ContenuRubrique     setNombreAffichage()   Sets the current record's "nombre_affichage" value
 * @method ContenuRubrique     setIdRubriqueMere()    Sets the current record's "id_rubrique_mere" value
 * @method ContenuRubrique     setFrTitre()           Sets the current record's "fr_titre" value
 * @method ContenuRubrique     setNomRepertoireFr()   Sets the current record's "nom_repertoire_fr" value
 * @method ContenuRubrique     setEnTitre()           Sets the current record's "en_titre" value
 * @method ContenuRubrique     setIdAdministrateur()  Sets the current record's "id_administrateur" value
 * @method ContenuRubrique     setPriorite()          Sets the current record's "priorite" value
 * @method ContenuRubrique     setDateCreation()      Sets the current record's "date_creation" value
 * @method ContenuRubrique     setDateModification()  Sets the current record's "date_modification" value
 * @method ContenuRubrique     setLienUrl()           Sets the current record's "lien_url" value
 * @method ContenuRubrique     setIdPerm()            Sets the current record's "id_perm" value
 * @method ContenuRubrique     setContenuRubrique()   Sets the current record's "ContenuRubrique" value
 * @method ContenuRubrique     setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method ContenuRubrique     setSfGuardPermission() Sets the current record's "sfGuardPermission" value
 * @method ContenuRubrique     setContenu()           Sets the current record's "Contenu" collection
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContenuRubrique extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contenu_rubrique');
        $this->hasColumn('id_rubrique', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_site', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nombre_affichage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_rubrique_mere', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fr_titre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('nom_repertoire_fr', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('en_titre', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('id_administrateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('priorite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('lien_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_perm', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContenuRubrique', array(
             'local' => 'id_rubrique_mere',
             'foreign' => 'id_rubrique'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'id_administrateur',
             'foreign' => 'id'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'id_perm',
             'foreign' => 'id'));

        $this->hasMany('Contenu', array(
             'local' => 'id_rubrique',
             'foreign' => 'id_rubrique_parente'));
    }
}