<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CovoitureurAmis', 'dbrmv3');

/**
 * BaseCovoitureurAmis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_covoitureur
 * @property integer $id_covoitureur_amis
 * @property integer $id_site
 * @property string $commentaire
 * @property float $note
 * @property timestamp $date_insert
 * @property integer $valide_message
 * @property Covoitureur $Covoitureur
 * @property SiteClient $SiteClient
 * 
 * @method integer         getIdCovoitureur()       Returns the current record's "id_covoitureur" value
 * @method integer         getIdCovoitureurAmis()   Returns the current record's "id_covoitureur_amis" value
 * @method integer         getIdSite()              Returns the current record's "id_site" value
 * @method string          getCommentaire()         Returns the current record's "commentaire" value
 * @method float           getNote()                Returns the current record's "note" value
 * @method timestamp       getDateInsert()          Returns the current record's "date_insert" value
 * @method integer         getValideMessage()       Returns the current record's "valide_message" value
 * @method Covoitureur     getCovoitureur()         Returns the current record's "Covoitureur" value
 * @method SiteClient      getSiteClient()          Returns the current record's "SiteClient" value
 * @method CovoitureurAmis setIdCovoitureur()       Sets the current record's "id_covoitureur" value
 * @method CovoitureurAmis setIdCovoitureurAmis()   Sets the current record's "id_covoitureur_amis" value
 * @method CovoitureurAmis setIdSite()              Sets the current record's "id_site" value
 * @method CovoitureurAmis setCommentaire()         Sets the current record's "commentaire" value
 * @method CovoitureurAmis setNote()                Sets the current record's "note" value
 * @method CovoitureurAmis setDateInsert()          Sets the current record's "date_insert" value
 * @method CovoitureurAmis setValideMessage()       Sets the current record's "valide_message" value
 * @method CovoitureurAmis setCovoitureur()         Sets the current record's "Covoitureur" value
 * @method CovoitureurAmis setSiteClient()          Sets the current record's "SiteClient" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCovoitureurAmis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('covoitureur_amis');
        $this->hasColumn('id_covoitureur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_covoitureur_amis', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_site', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('note', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('date_insert', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('valide_message', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Covoitureur', array(
             'local' => 'id_covoitureur_amis',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('SiteClient', array(
             'local' => 'id_site',
             'foreign' => 'id_site_client'));
    }
}