<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WysiNewsletterCategorie', 'dbrmv3');

/**
 * BaseWysiNewsletterCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_newsletter_categorie
 * @property string $fr_titre
 * @property integer $etat
 * @property integer $id_administrateur
 * 
 * @method integer                 getIdNewsletterCategorie()   Returns the current record's "id_newsletter_categorie" value
 * @method string                  getFrTitre()                 Returns the current record's "fr_titre" value
 * @method integer                 getEtat()                    Returns the current record's "etat" value
 * @method integer                 getIdAdministrateur()        Returns the current record's "id_administrateur" value
 * @method WysiNewsletterCategorie setIdNewsletterCategorie()   Sets the current record's "id_newsletter_categorie" value
 * @method WysiNewsletterCategorie setFrTitre()                 Sets the current record's "fr_titre" value
 * @method WysiNewsletterCategorie setEtat()                    Sets the current record's "etat" value
 * @method WysiNewsletterCategorie setIdAdministrateur()        Sets the current record's "id_administrateur" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWysiNewsletterCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wysi_newsletter_categorie');
        $this->hasColumn('id_newsletter_categorie', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fr_titre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_administrateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}