<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CovoitureurCentreInteret', 'dbrmv3');

/**
 * BaseCovoitureurCentreInteret
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_centre_interet
 * @property integer $id_utilisateur
 * @property CentreInteret $CentreInteret
 * @property Covoitureur $Covoitureur
 * 
 * @method integer                  getId()                Returns the current record's "id" value
 * @method integer                  getIdCentreInteret()   Returns the current record's "id_centre_interet" value
 * @method integer                  getIdUtilisateur()     Returns the current record's "id_utilisateur" value
 * @method CentreInteret            getCentreInteret()     Returns the current record's "CentreInteret" value
 * @method Covoitureur              getCovoitureur()       Returns the current record's "Covoitureur" value
 * @method CovoitureurCentreInteret setId()                Sets the current record's "id" value
 * @method CovoitureurCentreInteret setIdCentreInteret()   Sets the current record's "id_centre_interet" value
 * @method CovoitureurCentreInteret setIdUtilisateur()     Sets the current record's "id_utilisateur" value
 * @method CovoitureurCentreInteret setCentreInteret()     Sets the current record's "CentreInteret" value
 * @method CovoitureurCentreInteret setCovoitureur()       Sets the current record's "Covoitureur" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCovoitureurCentreInteret extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('covoitureur_centre_interet');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_centre_interet', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CentreInteret', array(
             'local' => 'id_centre_interet',
             'foreign' => 'id_centre_interet'));

        $this->hasOne('Covoitureur', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateur'));
    }
}