<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CentreInteret', 'dbrmv3');

/**
 * BaseCentreInteret
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_centre_interet
 * @property string $cle
 * @property integer $etat
 * @property timestamp $date_creation
 * @property string $libelle
 * @property string $description
 * @property string $libelle_all
 * @property string $libelle_fra
 * @property string $libelle_ang
 * @property string $libelle_nee
 * @property string $libelle_bre
 * @property string $libelle_eng
 * @property CovoitureurCentreInteret $CovoitureurCentreInteret
 * 
 * @method integer                  getIdCentreInteret()          Returns the current record's "id_centre_interet" value
 * @method string                   getCle()                      Returns the current record's "cle" value
 * @method integer                  getEtat()                     Returns the current record's "etat" value
 * @method timestamp                getDateCreation()             Returns the current record's "date_creation" value
 * @method string                   getLibelle()                  Returns the current record's "libelle" value
 * @method string                   getDescription()              Returns the current record's "description" value
 * @method string                   getLibelleAll()               Returns the current record's "libelle_all" value
 * @method string                   getLibelleFra()               Returns the current record's "libelle_fra" value
 * @method string                   getLibelleAng()               Returns the current record's "libelle_ang" value
 * @method string                   getLibelleNee()               Returns the current record's "libelle_nee" value
 * @method string                   getLibelleBre()               Returns the current record's "libelle_bre" value
 * @method string                   getLibelleEng()               Returns the current record's "libelle_eng" value
 * @method CovoitureurCentreInteret getCovoitureurCentreInteret() Returns the current record's "CovoitureurCentreInteret" value
 * @method CentreInteret            setIdCentreInteret()          Sets the current record's "id_centre_interet" value
 * @method CentreInteret            setCle()                      Sets the current record's "cle" value
 * @method CentreInteret            setEtat()                     Sets the current record's "etat" value
 * @method CentreInteret            setDateCreation()             Sets the current record's "date_creation" value
 * @method CentreInteret            setLibelle()                  Sets the current record's "libelle" value
 * @method CentreInteret            setDescription()              Sets the current record's "description" value
 * @method CentreInteret            setLibelleAll()               Sets the current record's "libelle_all" value
 * @method CentreInteret            setLibelleFra()               Sets the current record's "libelle_fra" value
 * @method CentreInteret            setLibelleAng()               Sets the current record's "libelle_ang" value
 * @method CentreInteret            setLibelleNee()               Sets the current record's "libelle_nee" value
 * @method CentreInteret            setLibelleBre()               Sets the current record's "libelle_bre" value
 * @method CentreInteret            setLibelleEng()               Sets the current record's "libelle_eng" value
 * @method CentreInteret            setCovoitureurCentreInteret() Sets the current record's "CovoitureurCentreInteret" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCentreInteret extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('centre_interet');
        $this->hasColumn('id_centre_interet', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_all', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_fra', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_ang', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_nee', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_bre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_eng', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CovoitureurCentreInteret', array(
             'local' => 'id_centre_interet',
             'foreign' => 'id_centre_interet'));
    }
}