<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpActionEtb', 'dbcvp');

/**
 * BaseCpActionEtb
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cp_action_etb_id
 * @property string $cp_action_etb_detail
 * @property timestamp $cp_action_etb_date_creation
 * @property timestamp $cp_action_etb_date_modification
 * @property date $cp_action_etb_date_echeance
 * @property integer $cp_action_etb_cp_type_action_id
 * @property integer $cp_action_etb_cp_etablissement_id
 * @property integer $cp_action_etb_user_id
 * @property integer $cp_action_etb_cp_contact_id
 * @property CpTypeAction $CpTypeAction
 * @property CpEtablissement $CpEtablissement
 * @property CpContact $CpContact
 * @property sfGuardUser $User
 * 
 * @method integer         getCpActionEtbId()                     Returns the current record's "cp_action_etb_id" value
 * @method string          getCpActionEtbDetail()                 Returns the current record's "cp_action_etb_detail" value
 * @method timestamp       getCpActionEtbDateCreation()           Returns the current record's "cp_action_etb_date_creation" value
 * @method timestamp       getCpActionEtbDateModification()       Returns the current record's "cp_action_etb_date_modification" value
 * @method date            getCpActionEtbDateEcheance()           Returns the current record's "cp_action_etb_date_echeance" value
 * @method integer         getCpActionEtbCpTypeActionId()         Returns the current record's "cp_action_etb_cp_type_action_id" value
 * @method integer         getCpActionEtbCpEtablissementId()      Returns the current record's "cp_action_etb_cp_etablissement_id" value
 * @method integer         getCpActionEtbUserId()                 Returns the current record's "cp_action_etb_user_id" value
 * @method integer         getCpActionEtbCpContactId()            Returns the current record's "cp_action_etb_cp_contact_id" value
 * @method CpTypeAction    getCpTypeAction()                      Returns the current record's "CpTypeAction" value
 * @method CpEtablissement getCpEtablissement()                   Returns the current record's "CpEtablissement" value
 * @method CpContact       getCpContact()                         Returns the current record's "CpContact" value
 * @method sfGuardUser     getUser()                              Returns the current record's "User" value
 * @method CpActionEtb     setCpActionEtbId()                     Sets the current record's "cp_action_etb_id" value
 * @method CpActionEtb     setCpActionEtbDetail()                 Sets the current record's "cp_action_etb_detail" value
 * @method CpActionEtb     setCpActionEtbDateCreation()           Sets the current record's "cp_action_etb_date_creation" value
 * @method CpActionEtb     setCpActionEtbDateModification()       Sets the current record's "cp_action_etb_date_modification" value
 * @method CpActionEtb     setCpActionEtbDateEcheance()           Sets the current record's "cp_action_etb_date_echeance" value
 * @method CpActionEtb     setCpActionEtbCpTypeActionId()         Sets the current record's "cp_action_etb_cp_type_action_id" value
 * @method CpActionEtb     setCpActionEtbCpEtablissementId()      Sets the current record's "cp_action_etb_cp_etablissement_id" value
 * @method CpActionEtb     setCpActionEtbUserId()                 Sets the current record's "cp_action_etb_user_id" value
 * @method CpActionEtb     setCpActionEtbCpContactId()            Sets the current record's "cp_action_etb_cp_contact_id" value
 * @method CpActionEtb     setCpTypeAction()                      Sets the current record's "CpTypeAction" value
 * @method CpActionEtb     setCpEtablissement()                   Sets the current record's "CpEtablissement" value
 * @method CpActionEtb     setCpContact()                         Sets the current record's "CpContact" value
 * @method CpActionEtb     setUser()                              Sets the current record's "User" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpActionEtb extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cp_action_etb');
        $this->hasColumn('cp_action_etb_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_etb_detail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cp_action_etb_date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_etb_date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_etb_date_echeance', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_etb_cp_type_action_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_etb_cp_etablissement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_etb_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_etb_cp_contact_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CpTypeAction', array(
             'local' => 'cp_action_etb_cp_type_action_id',
             'foreign' => 'cp_type_action_id'));

        $this->hasOne('CpEtablissement', array(
             'local' => 'cp_action_etb_cp_etablissement_id',
             'foreign' => 'cp_etablissement_id'));

        $this->hasOne('CpContact', array(
             'local' => 'cp_action_etb_cp_contact_id',
             'foreign' => 'cp_contact_id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'cp_action_etb_user_id',
             'foreign' => 'id'));
    }
}