<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrajetEtape', 'dbrmv3');

/**
 * BaseTrajetEtape
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_trajet_etape
 * @property integer $id_trajet
 * @property integer $id_lieu
 * @property integer $id_lieu_2
 * @property integer $id_lieu_pays
 * @property integer $type
 * @property string $autre
 * @property integer $position
 * 
 * @method integer     getIdTrajetEtape()   Returns the current record's "id_trajet_etape" value
 * @method integer     getIdTrajet()        Returns the current record's "id_trajet" value
 * @method integer     getIdLieu()          Returns the current record's "id_lieu" value
 * @method integer     getIdLieu2()         Returns the current record's "id_lieu_2" value
 * @method integer     getIdLieuPays()      Returns the current record's "id_lieu_pays" value
 * @method integer     getType()            Returns the current record's "type" value
 * @method string      getAutre()           Returns the current record's "autre" value
 * @method integer     getPosition()        Returns the current record's "position" value
 * @method TrajetEtape setIdTrajetEtape()   Sets the current record's "id_trajet_etape" value
 * @method TrajetEtape setIdTrajet()        Sets the current record's "id_trajet" value
 * @method TrajetEtape setIdLieu()          Sets the current record's "id_lieu" value
 * @method TrajetEtape setIdLieu2()         Sets the current record's "id_lieu_2" value
 * @method TrajetEtape setIdLieuPays()      Sets the current record's "id_lieu_pays" value
 * @method TrajetEtape setType()            Sets the current record's "type" value
 * @method TrajetEtape setAutre()           Sets the current record's "autre" value
 * @method TrajetEtape setPosition()        Sets the current record's "position" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrajetEtape extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trajet_etape');
        $this->hasColumn('id_trajet_etape', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_trajet', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_lieu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_lieu_2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_lieu_pays', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('autre', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}