<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Equipage', 'dbrmv3');

/**
 * BaseEquipage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_equipage
 * @property integer $id_trajet
 * @property integer $id_createur
 * @property integer $id_site
 * @property string $cle
 * @property integer $etat
 * @property timestamp $date_creation
 * @property string $nom_equipage
 * @property integer $id_ville_origine
 * @property integer $id_ville_destination
 * @property timestamp $date_modification
 * @property integer $id_profil
 * @property string $commentaires
 * @property Covoitureur $Covoitureur
 * @property Trajet $Trajet
 * @property SiteClient $SiteClient
 * @property VilleFr $VilleFr
 * @property Profile $Profile
 * @property EquipageCovoitureur $EquipageCovoitureur
 * 
 * @method integer             getIdEquipage()           Returns the current record's "id_equipage" value
 * @method integer             getIdTrajet()             Returns the current record's "id_trajet" value
 * @method integer             getIdCreateur()           Returns the current record's "id_createur" value
 * @method integer             getIdSite()               Returns the current record's "id_site" value
 * @method string              getCle()                  Returns the current record's "cle" value
 * @method integer             getEtat()                 Returns the current record's "etat" value
 * @method timestamp           getDateCreation()         Returns the current record's "date_creation" value
 * @method string              getNomEquipage()          Returns the current record's "nom_equipage" value
 * @method integer             getIdVilleOrigine()       Returns the current record's "id_ville_origine" value
 * @method integer             getIdVilleDestination()   Returns the current record's "id_ville_destination" value
 * @method timestamp           getDateModification()     Returns the current record's "date_modification" value
 * @method integer             getIdProfil()             Returns the current record's "id_profil" value
 * @method string              getCommentaires()         Returns the current record's "commentaires" value
 * @method Covoitureur         getCovoitureur()          Returns the current record's "Covoitureur" value
 * @method Trajet              getTrajet()               Returns the current record's "Trajet" value
 * @method SiteClient          getSiteClient()           Returns the current record's "SiteClient" value
 * @method VilleFr             getVilleFr()              Returns the current record's "VilleFr" value
 * @method Profile             getProfile()              Returns the current record's "Profile" value
 * @method EquipageCovoitureur getEquipageCovoitureur()  Returns the current record's "EquipageCovoitureur" value
 * @method Equipage            setIdEquipage()           Sets the current record's "id_equipage" value
 * @method Equipage            setIdTrajet()             Sets the current record's "id_trajet" value
 * @method Equipage            setIdCreateur()           Sets the current record's "id_createur" value
 * @method Equipage            setIdSite()               Sets the current record's "id_site" value
 * @method Equipage            setCle()                  Sets the current record's "cle" value
 * @method Equipage            setEtat()                 Sets the current record's "etat" value
 * @method Equipage            setDateCreation()         Sets the current record's "date_creation" value
 * @method Equipage            setNomEquipage()          Sets the current record's "nom_equipage" value
 * @method Equipage            setIdVilleOrigine()       Sets the current record's "id_ville_origine" value
 * @method Equipage            setIdVilleDestination()   Sets the current record's "id_ville_destination" value
 * @method Equipage            setDateModification()     Sets the current record's "date_modification" value
 * @method Equipage            setIdProfil()             Sets the current record's "id_profil" value
 * @method Equipage            setCommentaires()         Sets the current record's "commentaires" value
 * @method Equipage            setCovoitureur()          Sets the current record's "Covoitureur" value
 * @method Equipage            setTrajet()               Sets the current record's "Trajet" value
 * @method Equipage            setSiteClient()           Sets the current record's "SiteClient" value
 * @method Equipage            setVilleFr()              Sets the current record's "VilleFr" value
 * @method Equipage            setProfile()              Sets the current record's "Profile" value
 * @method Equipage            setEquipageCovoitureur()  Sets the current record's "EquipageCovoitureur" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipage');
        $this->hasColumn('id_equipage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_trajet', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_createur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_site', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nom_equipage', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_ville_origine', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ville_destination', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_profil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('commentaires', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Covoitureur', array(
             'local' => 'id_createur',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('Trajet', array(
             'local' => 'id_trajet',
             'foreign' => 'id_trajet'));

        $this->hasOne('SiteClient', array(
             'local' => 'id_site',
             'foreign' => 'id_site_client'));

        $this->hasOne('VilleFr', array(
             'local' => 'id_ville_destination',
             'foreign' => 'code_insee'));

        $this->hasOne('Profile', array(
             'local' => 'id_profil',
             'foreign' => 'id'));

        $this->hasOne('EquipageCovoitureur', array(
             'local' => 'id_equipage',
             'foreign' => 'id_equipage'));
    }
}