<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WysiNewsletterRetour', 'dbrmv3');

/**
 * BaseWysiNewsletterRetour
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_newsletter
 * @property integer $id_membre
 * @property string $mail_membre
 * @property timestamp $date
 * @property string $info
 * 
 * @method integer              getId()            Returns the current record's "id" value
 * @method integer              getIdNewsletter()  Returns the current record's "id_newsletter" value
 * @method integer              getIdMembre()      Returns the current record's "id_membre" value
 * @method string               getMailMembre()    Returns the current record's "mail_membre" value
 * @method timestamp            getDate()          Returns the current record's "date" value
 * @method string               getInfo()          Returns the current record's "info" value
 * @method WysiNewsletterRetour setId()            Sets the current record's "id" value
 * @method WysiNewsletterRetour setIdNewsletter()  Sets the current record's "id_newsletter" value
 * @method WysiNewsletterRetour setIdMembre()      Sets the current record's "id_membre" value
 * @method WysiNewsletterRetour setMailMembre()    Sets the current record's "mail_membre" value
 * @method WysiNewsletterRetour setDate()          Sets the current record's "date" value
 * @method WysiNewsletterRetour setInfo()          Sets the current record's "info" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWysiNewsletterRetour extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wysi_newsletter_retour');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_newsletter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_membre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mail_membre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}