<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/11 19:05:47

return array(
'dbrmv3' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecoov',
  'username' => 'coov_dba',
  'password' => 'yk0w9z',
  'name' => 'dbrmv3',
)),

'dbcvp' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=covoiturageplus',
  'username' => 'covoiturageplus',
  'password' => 'covoiturageplus',
  'name' => 'dbcvp',
)),);
