<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/11 19:05:47
sfConfig::add(array(
  'ex_meta_creator' => 'Roulez Malin',
  'ex_meta_title' => 'title',
  'ex_meta_subject' => 'subject',
  'ex_meta_description' => 'description',
  'ex_meta_keywords' => 'keywords',
  'ex_meta_category' => 'category',
));
