<?php
// auto-generated by sfViewConfigHandler
// date: 2012/10/11 19:05:48
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'covoitureur')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'plandusiteSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'covoitureur')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1, maximum-scale=1', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('skeleton.css', '', array ());
  $response->addStylesheet('layout.css', '', array ());
  $response->addStylesheet('/sfJqueryReloadedPlugin/css/ui-lightness/jquery-ui-1.7.3.custom.css', '', array ());
  $response->addJavascript('app.js', '', array ());
  $response->addJavascript('DD_roundies_0.0.2a-min.js', '', array ());
  $response->addJavascript('jExpand.js', '', array ());
  $response->addJavascript('jquery.bxSlider.min.js', '', array ());
  $response->addJavascript('jquery.easing.1.3.js', '', array ());
  $response->addJavascript('front.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker-fr.js', '', array ());
}
else if ($templateName.$this->viewName == 'plandusiteSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1, maximum-scale=1', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('skeleton.css', '', array ());
  $response->addStylesheet('layout.css', '', array ());
  $response->addStylesheet('/sfJqueryReloadedPlugin/css/ui-lightness/jquery-ui-1.7.3.custom.css', '', array ());
  $response->addStylesheet('sitemap.css', '', array ());
  $response->addJavascript('app.js', '', array ());
  $response->addJavascript('DD_roundies_0.0.2a-min.js', '', array ());
  $response->addJavascript('jExpand.js', '', array ());
  $response->addJavascript('jquery.bxSlider.min.js', '', array ());
  $response->addJavascript('jquery.easing.1.3.js', '', array ());
  $response->addJavascript('front.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker-fr.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1, maximum-scale=1', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('skeleton.css', '', array ());
  $response->addStylesheet('layout.css', '', array ());
  $response->addStylesheet('/sfJqueryReloadedPlugin/css/ui-lightness/jquery-ui-1.7.3.custom.css', '', array ());
  $response->addJavascript('app.js', '', array ());
  $response->addJavascript('DD_roundies_0.0.2a-min.js', '', array ());
  $response->addJavascript('jExpand.js', '', array ());
  $response->addJavascript('jquery.bxSlider.min.js', '', array ());
  $response->addJavascript('jquery.easing.1.3.js', '', array ());
  $response->addJavascript('front.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker-fr.js', '', array ());
}

