<?php

/**
 * ContactLesecomobilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactLesecomobilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactLesecomobilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactLesecomobiles');
    }
}