<?php

/**
 * CovoitureurEquipagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CovoitureurEquipagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CovoitureurEquipagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CovoitureurEquipages');
    }
}