<?php

/**
 * CpActionCtcTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpActionCtcTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpActionCtcTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpActionCtc')
                ;
    }
}