<?php

/**
 * CpActionCvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpActionCvTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CpActionCvTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('CpActionCv');
    }

    /*
     * liste les actions liée au covoitureur passé en argument
     */

    public function getActionsCovoitureur($id_utilisateur) {


        $q = Doctrine_Query::create()
                ->from('CpActionCv c')
                ->where('cp_action_cv_covoitureur_id = ?', $id_utilisateur)
                ->orderBy('cp_action_cv_date_creation DESC')
        ;

        return $q->execute();
    }
    
    /*
     * retourne le type_action de la dernière action pour un covoitureur et un trajet donné
     */
    
     public function getLastActionsCovoitureurStatut($id_utilisateur = null, $id_statut = null, $id_trajet = null) {
        if ($id_utilisateur == null || $id_statut == null || $id_trajet == null) {
            return 0;
        }

        $qt = Doctrine_Query::create()
                ->select('cp_action_cv_cp_type_action_id')
                ->from('CpActionCv cv')
                ->where('cv.cp_action_cv_trajet_id = ? ',$id_trajet)
                ->andWhere('cv.cp_action_cv_covoitureur_id = ?', $id_utilisateur)
                ->orderBy('cv.cp_action_cv_date_modification DESC')

        ;



        $type_action = $qt->fetchOne();
        //$vehicule = $qt->execute();

        if ($type_action) {
            return $type_action['cp_action_cv_cp_type_action_id'];
        } else {
            return 0;
        }

    }
    

}