<?php

/**
 * CpContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpContact');
    }
    
    /*
     * récupération de la liste des contacts pour un établissement
     */
    public static function getContactEtb($etb_id = null) {
        
            $q = Doctrine_Query::create()
                    ->from('CpContact cpc')
                    ->where('cpc.cp_contact_cp_etablissement_id = ?',$etb_id)
                    ;

        return $q;
    }

     /*
     * suppression des contacts pour un établissement
     */
    public static function getDeleteContactEtb($etb_id = null) {

            $q = Doctrine_Query::create()
                    ->delete()
                    ->from('CpContact cpc')
                    ->where('cpc.cp_contact_cp_etablissement_id = ?',$etb_id)
                    ;

        return $q;
    }
     
}