<?php

/**
 * CpTrajetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpTrajetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpTrajetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpTrajet');
    }
    
    
}