<?php

/**
 * DepartementFrancaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartementFrancaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartementFrancaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DepartementFrancais');
    }

    /*
     * retourne une jointure pour optimiser les requetes
     */
    public function retrieveBackendRegionList(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Region p');
        return $q;
    }
}