<?php

/**
 * LanguePageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguePageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LanguePageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LanguePage');
    }
}