<?php

/**
 * ParkingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParkingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParkingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parking');
    }
}