<?php

/**
 * TrajetEtapeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrajetEtapeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrajetEtapeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrajetEtape');
    }
}