<?php

/**
 * TrajetAlerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrajetAlerte extends BaseTrajetAlerte {
    /*
     * Récupération  de la ville de départ 
     */

    public function getDepartNomVille() {
        $departNomVille = "";
        $idDepart = substr($this->getIdDepart(), 3);

        if (!empty($idDepart) && is_numeric($idDepart)) {
            $ville = Doctrine_Core::getTable("VilleFr")->find($idDepart);
            $departNomVille = $ville->getNomVille();
            return $departNomVille;
            
        }
        return $departNomVille;
    }

    /*
     * Récupération de la ville de destination 
     */

    public function getDestinationNomVille() {
        $destinationNomVille = "";
        $idDestination = substr($this->getIdDestination(), 3);
        if (!empty($idDestination) && is_numeric($idDestination)) {
            $ville = Doctrine_Core::getTable("VilleFr")->find($idDestination);
            $destinationNomVille = $ville->getNomVille();
            return $destinationNomVille;
        }

        return $destinationNomVille;
    }

}
