<?php

/**
 * VehiculeMotorisationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculeMotorisationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculeMotorisationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculeMotorisation');
    }
}