<?php

/**
 * VehiculeCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculeCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculeCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculeCategorie');
    }
}