<?php

/**
 * VillePoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VillePoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VillePoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VillePo');
    }
}