<?php

/**
 * VilleItTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleItTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleItTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleIt');
    }
}