<?php

/**
 * VilleGmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleGmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleGmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleGm');
    }
}