<?php

/**
 * VilleIpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleIpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleIpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleIp');
    }
}