<?php

/**
 * WidgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WidgetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WidgetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Widget');
    }
}