<?php

/**
 * WysiNewsletterMembreEnvoyeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WysiNewsletterMembreEnvoyeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WysiNewsletterMembreEnvoyeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WysiNewsletterMembreEnvoye');
    }
}