<?php

/**
 * WysiNewsletterRetourTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WysiNewsletterRetourTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WysiNewsletterRetourTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WysiNewsletterRetour');
    }
}