<?php

/**
 * ZoneIndustrielleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZoneIndustrielleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZoneIndustrielleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZoneIndustrielle');
    }
}