<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/11 19:05:39
sfConfig::add(array(
  'ex_meta_creator' => 'Covoiturage Plus',
  'ex_meta_title' => 'Covoiturage Plus',
  'ex_meta_subject' => 'Covoiturage Plus',
  'ex_meta_description' => 'Covoiturage Plus',
  'ex_meta_keywords' => 'Covoiturage Plus',
  'ex_meta_category' => 'Covoiturage Plus',
));
