<?php

/**
 * Trajet filter form base class.
 *
 * @package    roulezmailn_v3
 * @subpackage filter
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseTrajetFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'bascule'                       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cle'                           => new sfWidgetFormFilterInput(),
      'etat'                          => new sfWidgetFormFilterInput(),
      'actif'                         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'etat_avant_bascule'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'site_confidentiel'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_utilisateur'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Covoitureur'), 'add_empty' => true)),
      'id_partenaire'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_offre_sur_site_partenaire'  => new sfWidgetFormFilterInput(),
      'id_site'                       => new sfWidgetFormFilterInput(),
      'id_site_site'                  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('SiteClient'), 'add_empty' => true)),
      'id_type_trajet'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('TrajetTypeCovoiturage'), 'add_empty' => true)),
      'id_nature_trajet'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_frequence'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_depart'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_depart2'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_depart_pays'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'depart_insee'                  => new sfWidgetFormFilterInput(),
      'depart_libelle'                => new sfWidgetFormFilterInput(),
      'depart_adresse'                => new sfWidgetFormFilterInput(),
      'depart_adresse_numero'         => new sfWidgetFormFilterInput(),
      'depart_code_postal'            => new sfWidgetFormFilterInput(),
      'depart_ville'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'depart_pays'                   => new sfWidgetFormFilterInput(),
      'depart_latitude'               => new sfWidgetFormFilterInput(),
      'depart_longitude'              => new sfWidgetFormFilterInput(),
      'depart_type'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'depart_autre_lieu'             => new sfWidgetFormFilterInput(),
      'id_destination'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('VilleFr'), 'add_empty' => true)),
      'id_destination2'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_destination_pays'           => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('PaysMonde'), 'add_empty' => true)),
      'destination_insee'             => new sfWidgetFormFilterInput(),
      'destination_libelle'           => new sfWidgetFormFilterInput(),
      'destination_adresse'           => new sfWidgetFormFilterInput(),
      'destination_adresse_numero'    => new sfWidgetFormFilterInput(),
      'destination_code_postal'       => new sfWidgetFormFilterInput(),
      'destination_ville'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'destination_pays'              => new sfWidgetFormFilterInput(),
      'destination_latitude'          => new sfWidgetFormFilterInput(),
      'destination_longitude'         => new sfWidgetFormFilterInput(),
      'destination_type'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'destination_autre_lieu'        => new sfWidgetFormFilterInput(),
      'etape1_ville'                  => new sfWidgetFormFilterInput(),
      'etape1_insee'                  => new sfWidgetFormFilterInput(),
      'etape_departement1'            => new sfWidgetFormFilterInput(),
      'etape1_lieu_id'                => new sfWidgetFormFilterInput(),
      'etape2_ville'                  => new sfWidgetFormFilterInput(),
      'etape2_insee'                  => new sfWidgetFormFilterInput(),
      'etape_departement2'            => new sfWidgetFormFilterInput(),
      'etape2_lieu_id'                => new sfWidgetFormFilterInput(),
      'etape3_ville'                  => new sfWidgetFormFilterInput(),
      'etape3_insee'                  => new sfWidgetFormFilterInput(),
      'etape_departement3'            => new sfWidgetFormFilterInput(),
      'etape3_lieu_id'                => new sfWidgetFormFilterInput(),
      'etape4_ville'                  => new sfWidgetFormFilterInput(),
      'etape4_insee'                  => new sfWidgetFormFilterInput(),
      'etape_departement4'            => new sfWidgetFormFilterInput(),
      'etape4_lieu_id'                => new sfWidgetFormFilterInput(),
      'etape5_ville'                  => new sfWidgetFormFilterInput(),
      'etape5_insee'                  => new sfWidgetFormFilterInput(),
      'etape_departement5'            => new sfWidgetFormFilterInput(),
      'etape5_lieu_id'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Lieu'), 'add_empty' => true)),
      'trajet_organisme'              => new sfWidgetFormFilterInput(),
      'km'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_zone_entreprise'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_evenement'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'zone_entreprise_autre'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'jour_unique_type_cov'          => new sfWidgetFormFilterInput(),
      'jour_unique_date'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'jour_unique_heure'             => new sfWidgetFormFilterInput(),
      'jour_unique_type_cov_retour'   => new sfWidgetFormFilterInput(),
      'jour_unique_date_retour'       => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'jour_unique_heure_retour'      => new sfWidgetFormFilterInput(),
      'jour_unique_retour'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'jour_unique_description'       => new sfWidgetFormFilterInput(),
      'lundi_type_cov'                => new sfWidgetFormFilterInput(),
      'lundi_etat'                    => new sfWidgetFormFilterInput(),
      'lundi_heure_depart'            => new sfWidgetFormFilterInput(),
      'lundi_heure_retour'            => new sfWidgetFormFilterInput(),
      'mardi_type_cov'                => new sfWidgetFormFilterInput(),
      'mardi_etat'                    => new sfWidgetFormFilterInput(),
      'mardi_heure_depart'            => new sfWidgetFormFilterInput(),
      'mardi_heure_retour'            => new sfWidgetFormFilterInput(),
      'mercredi_type_cov'             => new sfWidgetFormFilterInput(),
      'mercredi_etat'                 => new sfWidgetFormFilterInput(),
      'mercredi_heure_depart'         => new sfWidgetFormFilterInput(),
      'mercredi_heure_retour'         => new sfWidgetFormFilterInput(),
      'jeudi_type_cov'                => new sfWidgetFormFilterInput(),
      'jeudi_etat'                    => new sfWidgetFormFilterInput(),
      'jeudi_heure_depart'            => new sfWidgetFormFilterInput(),
      'jeudi_heure_retour'            => new sfWidgetFormFilterInput(),
      'vendredi_type_cov'             => new sfWidgetFormFilterInput(),
      'vendredi_etat'                 => new sfWidgetFormFilterInput(),
      'vendredi_heure_depart'         => new sfWidgetFormFilterInput(),
      'vendredi_heure_retour'         => new sfWidgetFormFilterInput(),
      'samedi_type_cov'               => new sfWidgetFormFilterInput(),
      'samedi_etat'                   => new sfWidgetFormFilterInput(),
      'samedi_heure_depart'           => new sfWidgetFormFilterInput(),
      'samedi_heure_retour'           => new sfWidgetFormFilterInput(),
      'dimanche_type_cov'             => new sfWidgetFormFilterInput(),
      'dimanche_etat'                 => new sfWidgetFormFilterInput(),
      'dimanche_heure_depart'         => new sfWidgetFormFilterInput(),
      'dimanche_heure_retour'         => new sfWidgetFormFilterInput(),
      'date_creation'                 => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'date_depublication'            => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'date_modification'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'date_verification'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'nombre_de_place'               => new sfWidgetFormFilterInput(),
      'mobilite_r'                    => new sfWidgetFormFilterInput(),
      'description'                   => new sfWidgetFormFilterInput(),
      'trajet_etudiant'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nombre_visualisation'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nombre_demande'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cout'                          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cout_passager'                 => new sfWidgetFormFilterInput(),
      'autoroute'                     => new sfWidgetFormFilterInput(),
      'autoroute_cout'                => new sfWidgetFormFilterInput(),
      'autoroute_text'                => new sfWidgetFormFilterInput(),
      'vehicule'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CovoitureurVehicule'), 'add_empty' => true)),
      'tolerance'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'url_retour'                    => new sfWidgetFormFilterInput(),
      'technique'                     => new sfWidgetFormFilterInput(),
      'visible_uniquement_partenaire' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_type_vehicule'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'volume_bagage'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'covoiturage_solidaire'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_equipage'                   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Equipage'), 'add_empty' => true)),
      'cp_trajet_id'                  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpTrajet'), 'add_empty' => true)),
      'presence_vehicule'             => new sfWidgetFormFilterInput(),
      'cp_type_action_statut_id'      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpTypeActionStatut'), 'add_empty' => true)),
    ));

    $this->setValidators(array(
      'bascule'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cle'                           => new sfValidatorPass(array('required' => false)),
      'etat'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'actif'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etat_avant_bascule'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'site_confidentiel'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_utilisateur'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Covoitureur'), 'column' => 'id_utilisateur')),
      'id_partenaire'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_offre_sur_site_partenaire'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_site'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_site_site'                  => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('SiteClient'), 'column' => 'id_site_client')),
      'id_type_trajet'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('TrajetTypeCovoiturage'), 'column' => 'id_type_covoiturage')),
      'id_nature_trajet'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_frequence'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_depart'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_depart2'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_depart_pays'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'depart_insee'                  => new sfValidatorPass(array('required' => false)),
      'depart_libelle'                => new sfValidatorPass(array('required' => false)),
      'depart_adresse'                => new sfValidatorPass(array('required' => false)),
      'depart_adresse_numero'         => new sfValidatorPass(array('required' => false)),
      'depart_code_postal'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'depart_ville'                  => new sfValidatorPass(array('required' => false)),
      'depart_pays'                   => new sfValidatorPass(array('required' => false)),
      'depart_latitude'               => new sfValidatorPass(array('required' => false)),
      'depart_longitude'              => new sfValidatorPass(array('required' => false)),
      'depart_type'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'depart_autre_lieu'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_destination'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('VilleFr'), 'column' => 'id_ville')),
      'id_destination2'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_destination_pays'           => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('PaysMonde'), 'column' => 'id_pays')),
      'destination_insee'             => new sfValidatorPass(array('required' => false)),
      'destination_libelle'           => new sfValidatorPass(array('required' => false)),
      'destination_adresse'           => new sfValidatorPass(array('required' => false)),
      'destination_adresse_numero'    => new sfValidatorPass(array('required' => false)),
      'destination_code_postal'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'destination_ville'             => new sfValidatorPass(array('required' => false)),
      'destination_pays'              => new sfValidatorPass(array('required' => false)),
      'destination_latitude'          => new sfValidatorPass(array('required' => false)),
      'destination_longitude'         => new sfValidatorPass(array('required' => false)),
      'destination_type'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'destination_autre_lieu'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape1_ville'                  => new sfValidatorPass(array('required' => false)),
      'etape1_insee'                  => new sfValidatorPass(array('required' => false)),
      'etape_departement1'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape1_lieu_id'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape2_ville'                  => new sfValidatorPass(array('required' => false)),
      'etape2_insee'                  => new sfValidatorPass(array('required' => false)),
      'etape_departement2'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape2_lieu_id'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape3_ville'                  => new sfValidatorPass(array('required' => false)),
      'etape3_insee'                  => new sfValidatorPass(array('required' => false)),
      'etape_departement3'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape3_lieu_id'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape4_ville'                  => new sfValidatorPass(array('required' => false)),
      'etape4_insee'                  => new sfValidatorPass(array('required' => false)),
      'etape_departement4'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape4_lieu_id'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape5_ville'                  => new sfValidatorPass(array('required' => false)),
      'etape5_insee'                  => new sfValidatorPass(array('required' => false)),
      'etape_departement5'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etape5_lieu_id'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Lieu'), 'column' => 'id_lieu')),
      'trajet_organisme'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'km'                            => new sfValidatorPass(array('required' => false)),
      'id_zone_entreprise'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_evenement'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'zone_entreprise_autre'         => new sfValidatorPass(array('required' => false)),
      'jour_unique_type_cov'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'jour_unique_date'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'jour_unique_heure'             => new sfValidatorPass(array('required' => false)),
      'jour_unique_type_cov_retour'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'jour_unique_date_retour'       => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'jour_unique_heure_retour'      => new sfValidatorPass(array('required' => false)),
      'jour_unique_retour'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'jour_unique_description'       => new sfValidatorPass(array('required' => false)),
      'lundi_type_cov'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lundi_etat'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lundi_heure_depart'            => new sfValidatorPass(array('required' => false)),
      'lundi_heure_retour'            => new sfValidatorPass(array('required' => false)),
      'mardi_type_cov'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mardi_etat'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mardi_heure_depart'            => new sfValidatorPass(array('required' => false)),
      'mardi_heure_retour'            => new sfValidatorPass(array('required' => false)),
      'mercredi_type_cov'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mercredi_etat'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mercredi_heure_depart'         => new sfValidatorPass(array('required' => false)),
      'mercredi_heure_retour'         => new sfValidatorPass(array('required' => false)),
      'jeudi_type_cov'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'jeudi_etat'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'jeudi_heure_depart'            => new sfValidatorPass(array('required' => false)),
      'jeudi_heure_retour'            => new sfValidatorPass(array('required' => false)),
      'vendredi_type_cov'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'vendredi_etat'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'vendredi_heure_depart'         => new sfValidatorPass(array('required' => false)),
      'vendredi_heure_retour'         => new sfValidatorPass(array('required' => false)),
      'samedi_type_cov'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'samedi_etat'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'samedi_heure_depart'           => new sfValidatorPass(array('required' => false)),
      'samedi_heure_retour'           => new sfValidatorPass(array('required' => false)),
      'dimanche_type_cov'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dimanche_etat'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dimanche_heure_depart'         => new sfValidatorPass(array('required' => false)),
      'dimanche_heure_retour'         => new sfValidatorPass(array('required' => false)),
      'date_creation'                 => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'date_depublication'            => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'date_modification'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'date_verification'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'nombre_de_place'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mobilite_r'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'description'                   => new sfValidatorPass(array('required' => false)),
      'trajet_etudiant'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nombre_visualisation'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nombre_demande'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cout'                          => new sfValidatorPass(array('required' => false)),
      'cout_passager'                 => new sfValidatorPass(array('required' => false)),
      'autoroute'                     => new sfValidatorPass(array('required' => false)),
      'autoroute_cout'                => new sfValidatorPass(array('required' => false)),
      'autoroute_text'                => new sfValidatorPass(array('required' => false)),
      'vehicule'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CovoitureurVehicule'), 'column' => 'id_vehicule')),
      'tolerance'                     => new sfValidatorPass(array('required' => false)),
      'url_retour'                    => new sfValidatorPass(array('required' => false)),
      'technique'                     => new sfValidatorPass(array('required' => false)),
      'visible_uniquement_partenaire' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_type_vehicule'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'volume_bagage'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'covoiturage_solidaire'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_equipage'                   => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Equipage'), 'column' => 'id_equipage')),
      'cp_trajet_id'                  => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CpTrajet'), 'column' => 'cp_trajet_id')),
      'presence_vehicule'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cp_type_action_statut_id'      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CpTypeActionStatut'), 'column' => 'cp_type_action_statut_id')),
    ));

    $this->widgetSchema->setNameFormat('trajet_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Trajet';
  }

  public function getFields()
  {
    return array(
      'id_trajet'                     => 'Number',
      'bascule'                       => 'Number',
      'cle'                           => 'Text',
      'etat'                          => 'Number',
      'actif'                         => 'Number',
      'etat_avant_bascule'            => 'Number',
      'site_confidentiel'             => 'Number',
      'id_utilisateur'                => 'ForeignKey',
      'id_partenaire'                 => 'Number',
      'id_offre_sur_site_partenaire'  => 'Number',
      'id_site'                       => 'Number',
      'id_site_site'                  => 'ForeignKey',
      'id_type_trajet'                => 'ForeignKey',
      'id_nature_trajet'              => 'Number',
      'id_frequence'                  => 'Number',
      'id_depart'                     => 'Number',
      'id_depart2'                    => 'Number',
      'id_depart_pays'                => 'Number',
      'depart_insee'                  => 'Text',
      'depart_libelle'                => 'Text',
      'depart_adresse'                => 'Text',
      'depart_adresse_numero'         => 'Text',
      'depart_code_postal'            => 'Number',
      'depart_ville'                  => 'Text',
      'depart_pays'                   => 'Text',
      'depart_latitude'               => 'Text',
      'depart_longitude'              => 'Text',
      'depart_type'                   => 'Number',
      'depart_autre_lieu'             => 'Number',
      'id_destination'                => 'ForeignKey',
      'id_destination2'               => 'Number',
      'id_destination_pays'           => 'ForeignKey',
      'destination_insee'             => 'Text',
      'destination_libelle'           => 'Text',
      'destination_adresse'           => 'Text',
      'destination_adresse_numero'    => 'Text',
      'destination_code_postal'       => 'Number',
      'destination_ville'             => 'Text',
      'destination_pays'              => 'Text',
      'destination_latitude'          => 'Text',
      'destination_longitude'         => 'Text',
      'destination_type'              => 'Number',
      'destination_autre_lieu'        => 'Number',
      'etape1_ville'                  => 'Text',
      'etape1_insee'                  => 'Text',
      'etape_departement1'            => 'Number',
      'etape1_lieu_id'                => 'Number',
      'etape2_ville'                  => 'Text',
      'etape2_insee'                  => 'Text',
      'etape_departement2'            => 'Number',
      'etape2_lieu_id'                => 'Number',
      'etape3_ville'                  => 'Text',
      'etape3_insee'                  => 'Text',
      'etape_departement3'            => 'Number',
      'etape3_lieu_id'                => 'Number',
      'etape4_ville'                  => 'Text',
      'etape4_insee'                  => 'Text',
      'etape_departement4'            => 'Number',
      'etape4_lieu_id'                => 'Number',
      'etape5_ville'                  => 'Text',
      'etape5_insee'                  => 'Text',
      'etape_departement5'            => 'Number',
      'etape5_lieu_id'                => 'ForeignKey',
      'trajet_organisme'              => 'Number',
      'km'                            => 'Text',
      'id_zone_entreprise'            => 'Number',
      'id_evenement'                  => 'Number',
      'zone_entreprise_autre'         => 'Text',
      'jour_unique_type_cov'          => 'Number',
      'jour_unique_date'              => 'Date',
      'jour_unique_heure'             => 'Text',
      'jour_unique_type_cov_retour'   => 'Number',
      'jour_unique_date_retour'       => 'Date',
      'jour_unique_heure_retour'      => 'Text',
      'jour_unique_retour'            => 'Number',
      'jour_unique_description'       => 'Text',
      'lundi_type_cov'                => 'Number',
      'lundi_etat'                    => 'Number',
      'lundi_heure_depart'            => 'Text',
      'lundi_heure_retour'            => 'Text',
      'mardi_type_cov'                => 'Number',
      'mardi_etat'                    => 'Number',
      'mardi_heure_depart'            => 'Text',
      'mardi_heure_retour'            => 'Text',
      'mercredi_type_cov'             => 'Number',
      'mercredi_etat'                 => 'Number',
      'mercredi_heure_depart'         => 'Text',
      'mercredi_heure_retour'         => 'Text',
      'jeudi_type_cov'                => 'Number',
      'jeudi_etat'                    => 'Number',
      'jeudi_heure_depart'            => 'Text',
      'jeudi_heure_retour'            => 'Text',
      'vendredi_type_cov'             => 'Number',
      'vendredi_etat'                 => 'Number',
      'vendredi_heure_depart'         => 'Text',
      'vendredi_heure_retour'         => 'Text',
      'samedi_type_cov'               => 'Number',
      'samedi_etat'                   => 'Number',
      'samedi_heure_depart'           => 'Text',
      'samedi_heure_retour'           => 'Text',
      'dimanche_type_cov'             => 'Number',
      'dimanche_etat'                 => 'Number',
      'dimanche_heure_depart'         => 'Text',
      'dimanche_heure_retour'         => 'Text',
      'date_creation'                 => 'Date',
      'date_depublication'            => 'Date',
      'date_modification'             => 'Date',
      'date_verification'             => 'Date',
      'nombre_de_place'               => 'Number',
      'mobilite_r'                    => 'Number',
      'description'                   => 'Text',
      'trajet_etudiant'               => 'Number',
      'nombre_visualisation'          => 'Number',
      'nombre_demande'                => 'Number',
      'cout'                          => 'Text',
      'cout_passager'                 => 'Text',
      'autoroute'                     => 'Text',
      'autoroute_cout'                => 'Text',
      'autoroute_text'                => 'Text',
      'vehicule'                      => 'ForeignKey',
      'tolerance'                     => 'Text',
      'url_retour'                    => 'Text',
      'technique'                     => 'Text',
      'visible_uniquement_partenaire' => 'Number',
      'id_type_vehicule'              => 'Number',
      'volume_bagage'                 => 'Number',
      'covoiturage_solidaire'         => 'Number',
      'id_equipage'                   => 'ForeignKey',
      'cp_trajet_id'                  => 'ForeignKey',
      'presence_vehicule'             => 'Number',
      'cp_type_action_statut_id'      => 'ForeignKey',
    );
  }
}
