<?php

/**
 * Covoitureur filter form base class.
 *
 * @package    roulezmailn_v3
 * @subpackage filter
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseCovoitureurFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'cle'                         => new sfWidgetFormFilterInput(),
      'etat'                        => new sfWidgetFormFilterInput(),
      'etat_site_client_validation' => new sfWidgetFormFilterInput(),
      'date_creation'               => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'date_modification'           => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'date_fin'                    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'inscription_minute'          => new sfWidgetFormFilterInput(),
      'identifiant'                 => new sfWidgetFormFilterInput(),
      'mot_de_passe'                => new sfWidgetFormFilterInput(),
      'sexe'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'civilite'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nom'                         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prenom'                      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'adresse'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'code_postal'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ville'                       => new sfWidgetFormFilterInput(),
      'mail'                        => new sfWidgetFormFilterInput(),
      'mail_perso'                  => new sfWidgetFormFilterInput(),
      'telephone_mobile'            => new sfWidgetFormFilterInput(),
      'telephone'                   => new sfWidgetFormFilterInput(),
      'telephone_visible'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'telephone_autre'             => new sfWidgetFormFilterInput(),
      'societe'                     => new sfWidgetFormFilterInput(),
      'matricule'                   => new sfWidgetFormFilterInput(),
      'service'                     => new sfWidgetFormFilterInput(),
      'tranche_age'                 => new sfWidgetFormFilterInput(),
      'date_naissance'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'isMajeur'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'question'                    => new sfWidgetFormFilterInput(),
      'reponse'                     => new sfWidgetFormFilterInput(),
      'date_derniere_connexion'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'nombre_connexion'            => new sfWidgetFormFilterInput(),
      'permanente_connexion'        => new sfWidgetFormFilterInput(),
      'id_partenaire'               => new sfWidgetFormFilterInput(),
      'id_site_client'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'id_site_site'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('SiteClient'), 'add_empty' => true)),
      'etat_photo'                  => new sfWidgetFormFilterInput(),
      'file_photo'                  => new sfWidgetFormFilterInput(),
      'photo_ext'                   => new sfWidgetFormFilterInput(),
      'etat_video'                  => new sfWidgetFormFilterInput(),
      'newsletter'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tolere_fumeur'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tolere_animaux'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tolere_bagage'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tolere_musique'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tolere_discussion'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'note'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dirgrp'                      => new sfWidgetFormFilterInput(),
      'dptag'                       => new sfWidgetFormFilterInput(),
      'svcpdv'                      => new sfWidgetFormFilterInput(),
      'bascule'                     => new sfWidgetFormFilterInput(),
      'id_facebook'                 => new sfWidgetFormFilterInput(),
      'mise_en_relation_sms'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rsa'                         => new sfWidgetFormFilterInput(),
      'id_covoitureur_lien_site'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CovoitureurLienSite'), 'add_empty' => true)),
      'id_covoitureur_fonction'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CovoitureurFonction'), 'add_empty' => true)),
      'cp_etablissement_horaire_id' => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpEtablissementHoraire'), 'add_empty' => true)),
      'cp_etablissement_secteur_id' => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpEtablissementSecteur'), 'add_empty' => true)),
      'cp_etablissement_id'         => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CpEtablissement'), 'add_empty' => true)),
      'id_csp'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Csp'), 'add_empty' => true)),
      'lu_charte'                   => new sfWidgetFormFilterInput(),
      'ss_mail'                     => new sfWidgetFormFilterInput(),
      'ss_contact_covoit'           => new sfWidgetFormFilterInput(),
      'anonymat'                    => new sfWidgetFormFilterInput(),
      'possede_vehicule'            => new sfWidgetFormFilterInput(),
      'remarque'                    => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'cle'                         => new sfValidatorPass(array('required' => false)),
      'etat'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'etat_site_client_validation' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'date_creation'               => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'date_modification'           => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'date_fin'                    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'inscription_minute'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'identifiant'                 => new sfValidatorPass(array('required' => false)),
      'mot_de_passe'                => new sfValidatorPass(array('required' => false)),
      'sexe'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'civilite'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nom'                         => new sfValidatorPass(array('required' => false)),
      'prenom'                      => new sfValidatorPass(array('required' => false)),
      'adresse'                     => new sfValidatorPass(array('required' => false)),
      'code_postal'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ville'                       => new sfValidatorPass(array('required' => false)),
      'mail'                        => new sfValidatorPass(array('required' => false)),
      'mail_perso'                  => new sfValidatorPass(array('required' => false)),
      'telephone_mobile'            => new sfValidatorPass(array('required' => false)),
      'telephone'                   => new sfValidatorPass(array('required' => false)),
      'telephone_visible'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'telephone_autre'             => new sfValidatorPass(array('required' => false)),
      'societe'                     => new sfValidatorPass(array('required' => false)),
      'matricule'                   => new sfValidatorPass(array('required' => false)),
      'service'                     => new sfValidatorPass(array('required' => false)),
      'tranche_age'                 => new sfValidatorPass(array('required' => false)),
      'date_naissance'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'isMajeur'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'question'                    => new sfValidatorPass(array('required' => false)),
      'reponse'                     => new sfValidatorPass(array('required' => false)),
      'date_derniere_connexion'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'nombre_connexion'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'permanente_connexion'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_partenaire'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_site_client'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_site_site'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('SiteClient'), 'column' => 'id_site_client')),
      'etat_photo'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'file_photo'                  => new sfValidatorPass(array('required' => false)),
      'photo_ext'                   => new sfValidatorPass(array('required' => false)),
      'etat_video'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'newsletter'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tolere_fumeur'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tolere_animaux'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tolere_bagage'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tolere_musique'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tolere_discussion'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'note'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dirgrp'                      => new sfValidatorPass(array('required' => false)),
      'dptag'                       => new sfValidatorPass(array('required' => false)),
      'svcpdv'                      => new sfValidatorPass(array('required' => false)),
      'bascule'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_facebook'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mise_en_relation_sms'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rsa'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'id_covoitureur_lien_site'    => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CovoitureurLienSite'), 'column' => 'id_covoitureur_lien_site')),
      'id_covoitureur_fonction'     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CovoitureurFonction'), 'column' => 'id_covoitureur_fonction')),
      'cp_etablissement_horaire_id' => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CpEtablissementHoraire'), 'column' => 'cp_etablissement_horaire_id')),
      'cp_etablissement_secteur_id' => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CpEtablissementSecteur'), 'column' => 'cp_etablissement_secteur_id')),
      'cp_etablissement_id'         => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('CpEtablissement'), 'column' => 'cp_etablissement_id')),
      'id_csp'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Csp'), 'column' => 'id_csp')),
      'lu_charte'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ss_mail'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ss_contact_covoit'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'anonymat'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'possede_vehicule'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'remarque'                    => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('covoitureur_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Covoitureur';
  }

  public function getFields()
  {
    return array(
      'id_utilisateur'              => 'Number',
      'cle'                         => 'Text',
      'etat'                        => 'Number',
      'etat_site_client_validation' => 'Number',
      'date_creation'               => 'Date',
      'date_modification'           => 'Date',
      'date_fin'                    => 'Date',
      'inscription_minute'          => 'Number',
      'identifiant'                 => 'Text',
      'mot_de_passe'                => 'Text',
      'sexe'                        => 'Number',
      'civilite'                    => 'Number',
      'nom'                         => 'Text',
      'prenom'                      => 'Text',
      'adresse'                     => 'Text',
      'code_postal'                 => 'Number',
      'ville'                       => 'Text',
      'mail'                        => 'Text',
      'mail_perso'                  => 'Text',
      'telephone_mobile'            => 'Text',
      'telephone'                   => 'Text',
      'telephone_visible'           => 'Number',
      'telephone_autre'             => 'Text',
      'societe'                     => 'Text',
      'matricule'                   => 'Text',
      'service'                     => 'Text',
      'tranche_age'                 => 'Text',
      'date_naissance'              => 'Date',
      'isMajeur'                    => 'Number',
      'question'                    => 'Text',
      'reponse'                     => 'Text',
      'date_derniere_connexion'     => 'Date',
      'nombre_connexion'            => 'Number',
      'permanente_connexion'        => 'Number',
      'id_partenaire'               => 'Number',
      'id_site_client'              => 'Number',
      'id_site_site'                => 'ForeignKey',
      'etat_photo'                  => 'Number',
      'file_photo'                  => 'Text',
      'photo_ext'                   => 'Text',
      'etat_video'                  => 'Number',
      'newsletter'                  => 'Number',
      'tolere_fumeur'               => 'Number',
      'tolere_animaux'              => 'Number',
      'tolere_bagage'               => 'Number',
      'tolere_musique'              => 'Number',
      'tolere_discussion'           => 'Number',
      'note'                        => 'Number',
      'dirgrp'                      => 'Text',
      'dptag'                       => 'Text',
      'svcpdv'                      => 'Text',
      'bascule'                     => 'Number',
      'id_facebook'                 => 'Number',
      'mise_en_relation_sms'        => 'Number',
      'rsa'                         => 'Number',
      'id_covoitureur_lien_site'    => 'ForeignKey',
      'id_covoitureur_fonction'     => 'ForeignKey',
      'cp_etablissement_horaire_id' => 'ForeignKey',
      'cp_etablissement_secteur_id' => 'ForeignKey',
      'cp_etablissement_id'         => 'ForeignKey',
      'id_csp'                      => 'ForeignKey',
      'lu_charte'                   => 'Number',
      'ss_mail'                     => 'Number',
      'ss_contact_covoit'           => 'Number',
      'anonymat'                    => 'Number',
      'possede_vehicule'            => 'Number',
      'remarque'                    => 'Text',
    );
  }
}
