<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable {

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    /*
     * récupère la liste des utilisateur en fonction du site, sauf le super admin
     * 
     */

    public static function getListUserSite() {
        $q = Doctrine_Query::create()
                ->from('sfGuardUser su')
                ->leftJoin('su.Profile sp')
                ->where('su.is_super_admin = 0')
                ->andWhere('su.is_active = 1')
                ->andWhere('sp.id_site = ?', sfConfig::get('sf_id_site_client'))
        ;

        return $q;
    }

}
