<?php

/**
 * Description of TrajetTest
 *
 * @author RoulezMalin
 */
include(dirname(__FILE__) . '/../../bootstrap/Doctrine.php');

$t = new lime_test(4);
$t->pass('Test Unit OK!');

//Test sur un trajet vide
$t->is(Trajet::getTrajetById(0), array());

//Test si l'id n'est pas un nombre
$t->is(Trajet::getTrajetById(test), array());

//Test de la recuperation d'une entrée
$trajet1 = Array(
    'id_trajet' => '1',
    'bascule' => '1',
    'cle' => 'userese',
    'etat' => '1',
    'actif' => '0',
    'etat_avant_bascule' => '0',
    'site_confidentiel' => '0',
    'id_utilisateur' => '2',
    'id_partenaire' => '0',
    'id_offre_sur_site_partenaire' => '',
    'id_site' => '1',
    'id_site_site' => '0',
    'id_type_trajet' => '0',
    'id_nature_trajet' => '0',
    'id_frequence' => '1',
    'id_depart' => '0',
    'id_depart2' => '0',
    'id_depart_pays' => '0',
    'depart_insee' => 'fr-12103',
    'depart_libelle' => '8 rue d\\\'arvor, Plabennec,',
    'depart_adresse' => 'rue d\\\'arvor',
    'depart_adresse_numero' => '8',
    'depart_code_postal' => '29860',
    'depart_ville' => 'Plabennec',
    'depart_pays' => 'france',
    'depart_latitude' => '48.503133',
    'depart_longitude' => '-4.433081',
    'depart_type' => '0',
    'depart_autre_lieu' => '',
    'id_destination' => '0',
    'id_destination2' => '0',
    'id_destination_pays' => '0',
    'destination_insee' => 'fr-11969',
    'destination_libelle' => 'quai de la douane, Brest',
    'destination_adresse' => 'quai de la douane',
    'destination_adresse_numero' => '',
    'destination_code_postal' => '29200',
    'destination_ville' => 'Brest',
    'destination_pays' => 'france',
    'destination_latitude' => '48.381958',
    'destination_longitude' => '-4.484687',
    'destination_type' => '0',
    'destination_autre_lieu' => '',
    'etape1_ville' => 'Morlaix',
    'etape1_insee' => '',
    'etape_departement1' => '0',
    'etape2_ville' => ' ',
    'etape2_insee' => '',
    'etape_departement2' => '0',
    'etape3_ville' => '',
    'etape3_insee' => '',
    'etape_departement3' => '0',
    'etape4_ville' => '',
    'etape4_insee' => '',
    'etape_departement4' => '0',
    'etape5_ville' => '',
    'etape5_insee' => '',
    'etape_departement5' => '0',
    'trajet_organisme' => '',
    'km' => '',
    'id_zone_entreprise' => '0',
    'id_evenement' => '0',
    'zone_entreprise_autre' => '',
    'jour_unique_type_cov' => '0',
    'jour_unique_date' => '0000-00-00 00:00:00',
    'jour_unique_heure' => '00:00:00',
    'jour_unique_type_cov_retour' => '0',
    'jour_unique_date_retour' => '0000-00-00',
    'jour_unique_heure_retour' => '00:00:00',
    'jour_unique_retour' => '0',
    'jour_unique_description' => '',
    'lundi_type_cov' => '',
    'lundi_etat' => '1',
    'lundi_heure_depart' => '08:00:00',
    'lundi_heure_retour' => '08:15:00',
    'mardi_type_cov' => '',
    'mardi_etat' => '1',
    'mardi_heure_depart' => '08:00:00',
    'mardi_heure_retour' => '08:15:00',
    'mercredi_type_cov' => '',
    'mercredi_etat' => '1',
    'mercredi_heure_depart' => '08:00:00',
    'mercredi_heure_retour' => '08:15:00',
    'jeudi_type_cov' => '',
    'jeudi_etat' => '1',
    'jeudi_heure_depart' => '08:00:00',
    'jeudi_heure_retour' => '08:15:00',
    'vendredi_type_cov' => '',
    'vendredi_etat' => '1',
    'vendredi_heure_depart' => '08:00:00',
    'vendredi_heure_retour' => '08:15:00',
    'samedi_type_cov' => '',
    'samedi_etat' => '',
    'samedi_heure_depart' => '08:00:00',
    'samedi_heure_retour' => '18:00:00',
    'dimanche_type_cov' => '',
    'dimanche_etat' => '',
    'dimanche_heure_depart' => '08:00:00',
    'dimanche_heure_retour' => '18:00:00',
    'date_creation' => '2008-01-31 15:19:00',
    'date_depublication' => '0000-00-00',
    'date_modification' => '0000-00-00 00:00:00',
    'date_verification' => '0000-00-00 00:00:00',
    'nombre_de_place' => '1',
    'mobilite_r' => '',
    'description' => 'Pas cher, moins cher qu\\\'un jet !',
    'trajet_etudiant' => '0',
    'nombre_visualisation' => '0',
    'nombre_demande' => '0',
    'cout' => '10000 euros pour l\\\'annÃƒÆ’Ã‚Â©e',
    'cout_passager' => '',
    'autoroute' => '',
    'autoroute_cout' => '',
    'autoroute_text' => '',
    'vehicule' => '',
    'tolerance' => '0[2],1[2],2[2]',
    'url_retour' => 'Roulez malin',
    'technique' => '',
    'visible_uniquement_partenaire' => '0',
    'id_type_vehicule' => '0',
    'volume_bagage' => '0',
    'covoiturage_solidaire' => '0',);
$t->is(Trajet::getTrajetById(1), $trajet1);
?>
