generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user_profile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        display:
          "NONE":                   [id_site, initiales]
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
