<?php

/**
 * ConcoursLesecomobilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcoursLesecomobilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcoursLesecomobilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcoursLesecomobiles');
    }
}