<?php

/**
 * ContenuActualiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenuActualiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContenuActualiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContenuActualite');
    }
    
     /*
     * filtrage des Actualités en fonction du site (id_site)
     */
    public function getActualiteSite(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('ContenuActualite c');
        }

        $q->andWhere('c.id_site = ?', sfConfig::get('sf_id_site_client'));

        return $q;
    }
    
    /*
     * filtrage des Actualités en fonction du site (id_site)
     */
    public function getActualiteActiveSite(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('ContenuActualite c');
        }

        $q->andWhere('c.id_site = ?', sfConfig::get('sf_id_site_client'));
        $q->andWhere('c.etat = 1');
        $q->orderBy('date_publication DESC');

        return $q;
    }
    
    /*
     * Récupération de l'actualité de la page d'accueil
     */
    public  function getActualiteAccueil(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('ContenuActualite c');
        }

        $q->andWhere('c.id_site = ?', sfConfig::get('sf_id_site_client'));
        $q->andWhere('c.etat = 1');
                $q->andWhere('c.en_premiere_page = 1');
                $q->orderBy('c.position');
                $q->orderBy('c.date_creation DESC');
                
                //$q->limit('1');
                
        /*
        $q1 = Doctrine_Core::getTable('ContenuActualite')
                ->createQuery('ca')
                //->leftJoin('cr.Contenu c')
                ->where('ca.id_site = ?', sfConfig::get('sf_id_site_client'))
                ->andWhere('ca.etat = 1')
                ->andWhere('ca.en_premiere_page = 1')
                ->orderBy('ca.position')
                ->limit('1')
                ;
                //->addOrderBy('c.priorite');
*/
            //$this->actualite = $q1->fetchOne(); 
       // $this->actualite = $q1->execute(); 

        return $q->fetchOne();
    }
}