<?php

/**
 * CovoitureurFonctionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CovoitureurFonctionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CovoitureurFonctionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CovoitureurFonction');
    }
    
    /*
     * filtrage des Contenu en fonction du site (id_site)
     */
    public function getCovoitureurFonctionSite(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('CovoitureurFonction c');
        }

        $q->andWhere('c.id_site_client = ?', sfConfig::get('sf_id_site_client'));

        return $q;
    }
}