<?php

/**
 * CpContactStatutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpContactStatutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpContactStatutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpContactStatut');
    }
}