<?php

/**
 * CpEtablissementStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CpEtablissementStatut extends BaseCpEtablissementStatut
{
 public function __toString()
    {
        return $this->getCpEtablissementStatutNom();
    }
}