<?php

/**
 * CpTypeActionStatutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpTypeActionStatutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpTypeActionStatutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpTypeActionStatut');
    }
    
     /*
     * retourne les statut classé par ordre
      * 
      * @return object CpTypeActionStatutTable
     */
    public function getStatutParOrdre(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('CpTypeActionStatut ce');
        }

        $q->orderBy('ce.cp_type_action_statut_ordre ASC');

        return $q;
    }
}