<?php

/**
 * DroitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DroitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DroitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Droit');
    }
}