<?php

/**
 * LangueItemTradTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LangueItemTradTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LangueItemTradTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LangueItemTrad');
    }
}