<?php

/**
 * LieuTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LieuTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LieuTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LieuTest');
    }
}