<?php

/**
 * LogSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogSiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogSite');
    }
}