<?php

/**
 * QuartierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuartierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuartierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quartier');
    }
}