<?php

/**
 * StatistiqueCovoitureurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatistiqueCovoitureurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatistiqueCovoitureurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatistiqueCovoitureur');
    }
}