<?php

/**
 * VilleDaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleDaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleDaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleDa');
    }
}