<?php

/**
 * VilleEiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleEiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleEiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleEi');
    }
}