<?php

/**
 * VilleAsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleAsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleAsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleAs');
    }
}