<?php

/**
 * VilleHuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleHuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleHuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleHu');
    }
}