<?php

/**
 * VilleLuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleLuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleLuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleLu');
    }
}