<?php

/**
 * VilleSiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleSiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleSiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleSi');
    }
}