<?php

/**
 * VilleNlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleNlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleNlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleNl');
    }
}