<?php

/**
 * VilleSpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleSpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleSpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleSp');
    }
}