<?php

/**
 * VilleUpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleUpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleUpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleUp');
    }
}