<?php

/**
 * VilleNoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleNoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleNoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleNo');
    }
}