<?php

/**
 * VilleAnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleAnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleAnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleAn');
    }
}