<?php

/**
 * VilleSwTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleSwTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleSwTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VilleSw');
    }
}