<?php

/**
 * WysiNewsletterMembreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WysiNewsletterMembreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WysiNewsletterMembreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WysiNewsletterMembre');
    }
}