# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

editSuccess:
  stylesheets:    []  
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false,jquery.ui.addresspicker.js]
newSuccess:
  stylesheets:    []  
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false,jquery.ui.addresspicker.js]
editEvenementSuccess:
  stylesheets:    []  
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false,jquery.ui.addresspicker.js]
newEvenementSuccess:
  stylesheets:    []  
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false,jquery.ui.addresspicker.js]

