<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Csp', 'dbrmv3');

/**
 * BaseCsp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_csp
 * @property string $intitule
 * @property Doctrine_Collection $Covoitureur
 * 
 * @method integer             getIdCsp()       Returns the current record's "id_csp" value
 * @method string              getIntitule()    Returns the current record's "intitule" value
 * @method Doctrine_Collection getCovoitureur() Returns the current record's "Covoitureur" collection
 * @method Csp                 setIdCsp()       Sets the current record's "id_csp" value
 * @method Csp                 setIntitule()    Sets the current record's "intitule" value
 * @method Csp                 setCovoitureur() Sets the current record's "Covoitureur" collection
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCsp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csp');
        $this->hasColumn('id_csp', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Covoitureur', array(
             'local' => 'id_csp',
             'foreign' => 'id_csp'));
    }
}