<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContactLesecomobiles', 'dbrmv3');

/**
 * BaseContactLesecomobiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contact_id
 * @property string $contact_nom
 * @property string $contact_prenom
 * @property string $contact_mail
 * @property string $contact_adresse
 * @property string $contact_tel
 * @property string $contact_organisme
 * @property string $contact_fonction
 * @property string $contact_remarques
 * @property integer $contact_choixdate
 * 
 * @method integer              getContactId()         Returns the current record's "contact_id" value
 * @method string               getContactNom()        Returns the current record's "contact_nom" value
 * @method string               getContactPrenom()     Returns the current record's "contact_prenom" value
 * @method string               getContactMail()       Returns the current record's "contact_mail" value
 * @method string               getContactAdresse()    Returns the current record's "contact_adresse" value
 * @method string               getContactTel()        Returns the current record's "contact_tel" value
 * @method string               getContactOrganisme()  Returns the current record's "contact_organisme" value
 * @method string               getContactFonction()   Returns the current record's "contact_fonction" value
 * @method string               getContactRemarques()  Returns the current record's "contact_remarques" value
 * @method integer              getContactChoixdate()  Returns the current record's "contact_choixdate" value
 * @method ContactLesecomobiles setContactId()         Sets the current record's "contact_id" value
 * @method ContactLesecomobiles setContactNom()        Sets the current record's "contact_nom" value
 * @method ContactLesecomobiles setContactPrenom()     Sets the current record's "contact_prenom" value
 * @method ContactLesecomobiles setContactMail()       Sets the current record's "contact_mail" value
 * @method ContactLesecomobiles setContactAdresse()    Sets the current record's "contact_adresse" value
 * @method ContactLesecomobiles setContactTel()        Sets the current record's "contact_tel" value
 * @method ContactLesecomobiles setContactOrganisme()  Sets the current record's "contact_organisme" value
 * @method ContactLesecomobiles setContactFonction()   Sets the current record's "contact_fonction" value
 * @method ContactLesecomobiles setContactRemarques()  Sets the current record's "contact_remarques" value
 * @method ContactLesecomobiles setContactChoixdate()  Sets the current record's "contact_choixdate" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactLesecomobiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact_lesecomobiles');
        $this->hasColumn('contact_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contact_nom', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_prenom', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_mail', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_adresse', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_tel', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('contact_organisme', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_fonction', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_remarques', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('contact_choixdate', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}