<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VehiculeModele', 'dbrmv3');

/**
 * BaseVehiculeModele
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_modele
 * @property string $cle
 * @property integer $etat
 * @property timestamp $date_creation
 * @property string $nom_modele
 * @property string $description
 * @property integer $id_marque
 * @property VehiculeMarque $VehiculeMarque
 * @property CovoitureurVehicule $CovoitureurVehicule
 * 
 * @method integer             getIdModele()            Returns the current record's "id_modele" value
 * @method string              getCle()                 Returns the current record's "cle" value
 * @method integer             getEtat()                Returns the current record's "etat" value
 * @method timestamp           getDateCreation()        Returns the current record's "date_creation" value
 * @method string              getNomModele()           Returns the current record's "nom_modele" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getIdMarque()            Returns the current record's "id_marque" value
 * @method VehiculeMarque      getVehiculeMarque()      Returns the current record's "VehiculeMarque" value
 * @method CovoitureurVehicule getCovoitureurVehicule() Returns the current record's "CovoitureurVehicule" value
 * @method VehiculeModele      setIdModele()            Sets the current record's "id_modele" value
 * @method VehiculeModele      setCle()                 Sets the current record's "cle" value
 * @method VehiculeModele      setEtat()                Sets the current record's "etat" value
 * @method VehiculeModele      setDateCreation()        Sets the current record's "date_creation" value
 * @method VehiculeModele      setNomModele()           Sets the current record's "nom_modele" value
 * @method VehiculeModele      setDescription()         Sets the current record's "description" value
 * @method VehiculeModele      setIdMarque()            Sets the current record's "id_marque" value
 * @method VehiculeModele      setVehiculeMarque()      Sets the current record's "VehiculeMarque" value
 * @method VehiculeModele      setCovoitureurVehicule() Sets the current record's "CovoitureurVehicule" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculeModele extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicule_modele');
        $this->hasColumn('id_modele', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nom_modele', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_marque', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VehiculeMarque', array(
             'local' => 'id_marque',
             'foreign' => 'id_marque'));

        $this->hasOne('CovoitureurVehicule', array(
             'local' => 'id_modele',
             'foreign' => 'id_modele'));
    }
}