<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DemandeRenseignement', 'dbrmv3');

/**
 * BaseDemandeRenseignement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $demande_renseignement_id
 * @property string $demande_renseignement_civilite
 * @property string $demande_renseignement_nom
 * @property string $demande_renseignement_prenom
 * @property string $demande_renseignement_societe
 * @property string $demande_renseignement_fonction
 * @property string $demande_renseignement_adresse
 * @property string $demande_renseignement_cp
 * @property string $demande_renseignement_ville
 * @property string $demande_renseignement_pays
 * @property string $demande_renseignement_telephone
 * @property string $demande_renseignement_email
 * @property string $demande_renseignement_fax
 * @property string $demande_renseignement_texte
 * @property string $demande_renseignement_type
 * @property time $demande_renseignement_date_insert
 * @property integer $id_site_client
 * @property SiteClient $SiteClient
 * 
 * @method integer              getDemandeRenseignementId()            Returns the current record's "demande_renseignement_id" value
 * @method string               getDemandeRenseignementCivilite()      Returns the current record's "demande_renseignement_civilite" value
 * @method string               getDemandeRenseignementNom()           Returns the current record's "demande_renseignement_nom" value
 * @method string               getDemandeRenseignementPrenom()        Returns the current record's "demande_renseignement_prenom" value
 * @method string               getDemandeRenseignementSociete()       Returns the current record's "demande_renseignement_societe" value
 * @method string               getDemandeRenseignementFonction()      Returns the current record's "demande_renseignement_fonction" value
 * @method string               getDemandeRenseignementAdresse()       Returns the current record's "demande_renseignement_adresse" value
 * @method string               getDemandeRenseignementCp()            Returns the current record's "demande_renseignement_cp" value
 * @method string               getDemandeRenseignementVille()         Returns the current record's "demande_renseignement_ville" value
 * @method string               getDemandeRenseignementPays()          Returns the current record's "demande_renseignement_pays" value
 * @method string               getDemandeRenseignementTelephone()     Returns the current record's "demande_renseignement_telephone" value
 * @method string               getDemandeRenseignementEmail()         Returns the current record's "demande_renseignement_email" value
 * @method string               getDemandeRenseignementFax()           Returns the current record's "demande_renseignement_fax" value
 * @method string               getDemandeRenseignementTexte()         Returns the current record's "demande_renseignement_texte" value
 * @method string               getDemandeRenseignementType()          Returns the current record's "demande_renseignement_type" value
 * @method time                 getDemandeRenseignementDateInsert()    Returns the current record's "demande_renseignement_date_insert" value
 * @method integer              getIdSiteClient()                      Returns the current record's "id_site_client" value
 * @method SiteClient           getSiteClient()                        Returns the current record's "SiteClient" value
 * @method DemandeRenseignement setDemandeRenseignementId()            Sets the current record's "demande_renseignement_id" value
 * @method DemandeRenseignement setDemandeRenseignementCivilite()      Sets the current record's "demande_renseignement_civilite" value
 * @method DemandeRenseignement setDemandeRenseignementNom()           Sets the current record's "demande_renseignement_nom" value
 * @method DemandeRenseignement setDemandeRenseignementPrenom()        Sets the current record's "demande_renseignement_prenom" value
 * @method DemandeRenseignement setDemandeRenseignementSociete()       Sets the current record's "demande_renseignement_societe" value
 * @method DemandeRenseignement setDemandeRenseignementFonction()      Sets the current record's "demande_renseignement_fonction" value
 * @method DemandeRenseignement setDemandeRenseignementAdresse()       Sets the current record's "demande_renseignement_adresse" value
 * @method DemandeRenseignement setDemandeRenseignementCp()            Sets the current record's "demande_renseignement_cp" value
 * @method DemandeRenseignement setDemandeRenseignementVille()         Sets the current record's "demande_renseignement_ville" value
 * @method DemandeRenseignement setDemandeRenseignementPays()          Sets the current record's "demande_renseignement_pays" value
 * @method DemandeRenseignement setDemandeRenseignementTelephone()     Sets the current record's "demande_renseignement_telephone" value
 * @method DemandeRenseignement setDemandeRenseignementEmail()         Sets the current record's "demande_renseignement_email" value
 * @method DemandeRenseignement setDemandeRenseignementFax()           Sets the current record's "demande_renseignement_fax" value
 * @method DemandeRenseignement setDemandeRenseignementTexte()         Sets the current record's "demande_renseignement_texte" value
 * @method DemandeRenseignement setDemandeRenseignementType()          Sets the current record's "demande_renseignement_type" value
 * @method DemandeRenseignement setDemandeRenseignementDateInsert()    Sets the current record's "demande_renseignement_date_insert" value
 * @method DemandeRenseignement setIdSiteClient()                      Sets the current record's "id_site_client" value
 * @method DemandeRenseignement setSiteClient()                        Sets the current record's "SiteClient" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemandeRenseignement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demande_renseignement');
        $this->hasColumn('demande_renseignement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('demande_renseignement_civilite', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('demande_renseignement_nom', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('demande_renseignement_prenom', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('demande_renseignement_societe', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_fonction', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_adresse', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_cp', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_ville', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_pays', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_telephone', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('demande_renseignement_email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_fax', 'string', 25, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('demande_renseignement_texte', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('demande_renseignement_type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('demande_renseignement_date_insert', 'time', 25, array(
             'type' => 'time',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_site_client', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteClient', array(
             'local' => 'id_site_client',
             'foreign' => 'id_site_client'));
    }
}