<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CovoitureurFonction', 'dbrmv3');

/**
 * BaseCovoitureurFonction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_covoitureur_fonction
 * @property string $nom
 * @property timestamp $date_creation
 * @property integer $id_site_client
 * @property SiteClient $SiteClient
 * @property Covoitureur $Covoitureur
 * 
 * @method integer             getIdCovoitureurFonction()   Returns the current record's "id_covoitureur_fonction" value
 * @method string              getNom()                     Returns the current record's "nom" value
 * @method timestamp           getDateCreation()            Returns the current record's "date_creation" value
 * @method integer             getIdSiteClient()            Returns the current record's "id_site_client" value
 * @method SiteClient          getSiteClient()              Returns the current record's "SiteClient" value
 * @method Covoitureur         getCovoitureur()             Returns the current record's "Covoitureur" value
 * @method CovoitureurFonction setIdCovoitureurFonction()   Sets the current record's "id_covoitureur_fonction" value
 * @method CovoitureurFonction setNom()                     Sets the current record's "nom" value
 * @method CovoitureurFonction setDateCreation()            Sets the current record's "date_creation" value
 * @method CovoitureurFonction setIdSiteClient()            Sets the current record's "id_site_client" value
 * @method CovoitureurFonction setSiteClient()              Sets the current record's "SiteClient" value
 * @method CovoitureurFonction setCovoitureur()             Sets the current record's "Covoitureur" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCovoitureurFonction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('covoitureur_fonction');
        $this->hasColumn('id_covoitureur_fonction', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_site_client', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteClient', array(
             'local' => 'id_site_client',
             'foreign' => 'id_site_client'));

        $this->hasOne('Covoitureur', array(
             'local' => 'id_covoitureur_fonction',
             'foreign' => 'id_covoitureur_fonction'));
    }
}