<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DepartementFrancais', 'dbrmv3');

/**
 * BaseDepartementFrancais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_departement
 * @property integer $id_region
 * @property string $nom_departement
 * @property string $site_web_departement
 * @property Region $Region
 * 
 * @method integer             getIdDepartement()        Returns the current record's "id_departement" value
 * @method integer             getIdRegion()             Returns the current record's "id_region" value
 * @method string              getNomDepartement()       Returns the current record's "nom_departement" value
 * @method string              getSiteWebDepartement()   Returns the current record's "site_web_departement" value
 * @method Region              getRegion()               Returns the current record's "Region" value
 * @method DepartementFrancais setIdDepartement()        Sets the current record's "id_departement" value
 * @method DepartementFrancais setIdRegion()             Sets the current record's "id_region" value
 * @method DepartementFrancais setNomDepartement()       Sets the current record's "nom_departement" value
 * @method DepartementFrancais setSiteWebDepartement()   Sets the current record's "site_web_departement" value
 * @method DepartementFrancais setRegion()               Sets the current record's "Region" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartementFrancais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departement_francais');
        $this->hasColumn('id_departement', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_region', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nom_departement', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('site_web_departement', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'id_region',
             'foreign' => 'id_region'));
    }
}