<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpContactStatut', 'dbcvp');

/**
 * BaseCpContactStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cp_contact_statut_id
 * @property string $cp_contact_statut_libelle
 * @property Doctrine_Collection $CpContact
 * 
 * @method integer             getCpContactStatutId()         Returns the current record's "cp_contact_statut_id" value
 * @method string              getCpContactStatutLibelle()    Returns the current record's "cp_contact_statut_libelle" value
 * @method Doctrine_Collection getCpContact()                 Returns the current record's "CpContact" collection
 * @method CpContactStatut     setCpContactStatutId()         Sets the current record's "cp_contact_statut_id" value
 * @method CpContactStatut     setCpContactStatutLibelle()    Sets the current record's "cp_contact_statut_libelle" value
 * @method CpContactStatut     setCpContact()                 Sets the current record's "CpContact" collection
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpContactStatut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cp_contact_statut');
        $this->hasColumn('cp_contact_statut_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp_contact_statut_libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CpContact', array(
             'local' => 'cp_contact_statut_id',
             'foreign' => 'cp_contact_statut_id'));
    }
}