<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WysiNewsletterMembreEnvoye', 'dbrmv3');

/**
 * BaseWysiNewsletterMembreEnvoye
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_newsletter
 * @property string $mail
 * 
 * @method integer                    getId()            Returns the current record's "id" value
 * @method integer                    getIdNewsletter()  Returns the current record's "id_newsletter" value
 * @method string                     getMail()          Returns the current record's "mail" value
 * @method WysiNewsletterMembreEnvoye setId()            Sets the current record's "id" value
 * @method WysiNewsletterMembreEnvoye setIdNewsletter()  Sets the current record's "id_newsletter" value
 * @method WysiNewsletterMembreEnvoye setMail()          Sets the current record's "mail" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWysiNewsletterMembreEnvoye extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wysi_newsletter_membre_envoye');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_newsletter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mail', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}