<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActualiteAppartenantNewsletter', 'dbrmv3');

/**
 * BaseActualiteAppartenantNewsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_newsletter
 * @property integer $id_actualite
 * @property ContenuActualite $ContenuActualite
 * 
 * @method integer                        getIdNewsletter()     Returns the current record's "id_newsletter" value
 * @method integer                        getIdActualite()      Returns the current record's "id_actualite" value
 * @method ContenuActualite               getContenuActualite() Returns the current record's "ContenuActualite" value
 * @method ActualiteAppartenantNewsletter setIdNewsletter()     Sets the current record's "id_newsletter" value
 * @method ActualiteAppartenantNewsletter setIdActualite()      Sets the current record's "id_actualite" value
 * @method ActualiteAppartenantNewsletter setContenuActualite() Sets the current record's "ContenuActualite" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActualiteAppartenantNewsletter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actualite_appartenant_newsletter');
        $this->hasColumn('id_newsletter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_actualite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContenuActualite', array(
             'local' => 'id_actualite',
             'foreign' => 'id_actualite'));
    }
}