<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpEtablissementHoraire', 'dbcvp');

/**
 * BaseCpEtablissementHoraire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cp_etablissement_horaire_id
 * @property string $cp_etablissement_horaire_nom
 * @property integer $cp_etablissement_cp_etablissement_id
 * @property CpEtablissement $CpEtablissement
 * @property Covoitureur $Covoitureur
 * @property Doctrine_Collection $CpTrajet
 * 
 * @method integer                getCpEtablissementHoraireId()             Returns the current record's "cp_etablissement_horaire_id" value
 * @method string                 getCpEtablissementHoraireNom()            Returns the current record's "cp_etablissement_horaire_nom" value
 * @method integer                getCpEtablissementCpEtablissementId()     Returns the current record's "cp_etablissement_cp_etablissement_id" value
 * @method CpEtablissement        getCpEtablissement()                      Returns the current record's "CpEtablissement" value
 * @method Covoitureur            getCovoitureur()                          Returns the current record's "Covoitureur" value
 * @method Doctrine_Collection    getCpTrajet()                             Returns the current record's "CpTrajet" collection
 * @method CpEtablissementHoraire setCpEtablissementHoraireId()             Sets the current record's "cp_etablissement_horaire_id" value
 * @method CpEtablissementHoraire setCpEtablissementHoraireNom()            Sets the current record's "cp_etablissement_horaire_nom" value
 * @method CpEtablissementHoraire setCpEtablissementCpEtablissementId()     Sets the current record's "cp_etablissement_cp_etablissement_id" value
 * @method CpEtablissementHoraire setCpEtablissement()                      Sets the current record's "CpEtablissement" value
 * @method CpEtablissementHoraire setCovoitureur()                          Sets the current record's "Covoitureur" value
 * @method CpEtablissementHoraire setCpTrajet()                             Sets the current record's "CpTrajet" collection
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpEtablissementHoraire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cp_etablissement_horaire');
        $this->hasColumn('cp_etablissement_horaire_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp_etablissement_horaire_nom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cp_etablissement_cp_etablissement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CpEtablissement', array(
             'local' => 'cp_etablissement_cp_etablissement_id',
             'foreign' => 'cp_etablissement_id'));

        $this->hasOne('Covoitureur', array(
             'local' => 'cp_etablissement_horaire_id',
             'foreign' => 'cp_etablissement_horaire_id'));

        $this->hasMany('CpTrajet', array(
             'local' => 'cp_etablissement_horaire_id',
             'foreign' => 'cp_etablissement_horaire_id'));
    }
}