<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LieuType', 'dbrmv3');

/**
 * BaseLieuType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_lieu_type
 * @property string $libelle_lieu_type
 * @property string $libelle_lieu_type_neer
 * @property integer $version_light
 * @property integer $id_site_client
 * @property integer $evenement
 * @property SiteClient $SiteClient
 * @property Lieu $Lieu
 * @property LieuTest $LieuTest
 * 
 * @method integer    getIdLieuType()             Returns the current record's "id_lieu_type" value
 * @method string     getLibelleLieuType()        Returns the current record's "libelle_lieu_type" value
 * @method string     getLibelleLieuTypeNeer()    Returns the current record's "libelle_lieu_type_neer" value
 * @method integer    getVersionLight()           Returns the current record's "version_light" value
 * @method integer    getIdSiteClient()           Returns the current record's "id_site_client" value
 * @method integer    getEvenement()              Returns the current record's "evenement" value
 * @method SiteClient getSiteClient()             Returns the current record's "SiteClient" value
 * @method Lieu       getLieu()                   Returns the current record's "Lieu" value
 * @method LieuTest   getLieuTest()               Returns the current record's "LieuTest" value
 * @method LieuType   setIdLieuType()             Sets the current record's "id_lieu_type" value
 * @method LieuType   setLibelleLieuType()        Sets the current record's "libelle_lieu_type" value
 * @method LieuType   setLibelleLieuTypeNeer()    Sets the current record's "libelle_lieu_type_neer" value
 * @method LieuType   setVersionLight()           Sets the current record's "version_light" value
 * @method LieuType   setIdSiteClient()           Sets the current record's "id_site_client" value
 * @method LieuType   setEvenement()              Sets the current record's "evenement" value
 * @method LieuType   setSiteClient()             Sets the current record's "SiteClient" value
 * @method LieuType   setLieu()                   Sets the current record's "Lieu" value
 * @method LieuType   setLieuTest()               Sets the current record's "LieuTest" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLieuType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lieu_type');
        $this->hasColumn('id_lieu_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('libelle_lieu_type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('libelle_lieu_type_neer', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => ' ',
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('version_light', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_site_client', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('evenement', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteClient', array(
             'local' => 'id_site_client',
             'foreign' => 'id_site_client'));

        $this->hasOne('Lieu', array(
             'local' => 'id_lieu_type',
             'foreign' => 'id_lieu_type'));

        $this->hasOne('LieuTest', array(
             'local' => 'id_lieu_type',
             'foreign' => 'id_lieu_type'));
    }
}