<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpActionCtc', 'dbcvp');

/**
 * BaseCpActionCtc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cp_action_ctc_id
 * @property string $cp_action_ctc_detail
 * @property timestamp $cp_action_ctc_date_creation
 * @property timestamp $cp_action_ctc_date_modification
 * @property date $cp_action_ctc_date_echeance
 * @property integer $cp_action_ctc_cp_type_action_id
 * @property integer $cp_action_ctc_cp_contact_id
 * @property integer $cp_action_ctc_user_id
 * @property CpContact $CpContact
 * @property CpTypeAction $CpTypeAction
 * @property sfGuardUser $User
 * 
 * @method integer      getCpActionCtcId()                   Returns the current record's "cp_action_ctc_id" value
 * @method string       getCpActionCtcDetail()               Returns the current record's "cp_action_ctc_detail" value
 * @method timestamp    getCpActionCtcDateCreation()         Returns the current record's "cp_action_ctc_date_creation" value
 * @method timestamp    getCpActionCtcDateModification()     Returns the current record's "cp_action_ctc_date_modification" value
 * @method date         getCpActionCtcDateEcheance()         Returns the current record's "cp_action_ctc_date_echeance" value
 * @method integer      getCpActionCtcCpTypeActionId()       Returns the current record's "cp_action_ctc_cp_type_action_id" value
 * @method integer      getCpActionCtcCpContactId()          Returns the current record's "cp_action_ctc_cp_contact_id" value
 * @method integer      getCpActionCtcUserId()               Returns the current record's "cp_action_ctc_user_id" value
 * @method CpContact    getCpContact()                       Returns the current record's "CpContact" value
 * @method CpTypeAction getCpTypeAction()                    Returns the current record's "CpTypeAction" value
 * @method sfGuardUser  getUser()                            Returns the current record's "User" value
 * @method CpActionCtc  setCpActionCtcId()                   Sets the current record's "cp_action_ctc_id" value
 * @method CpActionCtc  setCpActionCtcDetail()               Sets the current record's "cp_action_ctc_detail" value
 * @method CpActionCtc  setCpActionCtcDateCreation()         Sets the current record's "cp_action_ctc_date_creation" value
 * @method CpActionCtc  setCpActionCtcDateModification()     Sets the current record's "cp_action_ctc_date_modification" value
 * @method CpActionCtc  setCpActionCtcDateEcheance()         Sets the current record's "cp_action_ctc_date_echeance" value
 * @method CpActionCtc  setCpActionCtcCpTypeActionId()       Sets the current record's "cp_action_ctc_cp_type_action_id" value
 * @method CpActionCtc  setCpActionCtcCpContactId()          Sets the current record's "cp_action_ctc_cp_contact_id" value
 * @method CpActionCtc  setCpActionCtcUserId()               Sets the current record's "cp_action_ctc_user_id" value
 * @method CpActionCtc  setCpContact()                       Sets the current record's "CpContact" value
 * @method CpActionCtc  setCpTypeAction()                    Sets the current record's "CpTypeAction" value
 * @method CpActionCtc  setUser()                            Sets the current record's "User" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpActionCtc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cp_action_ctc');
        $this->hasColumn('cp_action_ctc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_ctc_detail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cp_action_ctc_date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_ctc_date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_ctc_date_echeance', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_ctc_cp_type_action_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_ctc_cp_contact_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_ctc_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CpContact', array(
             'local' => 'cp_action_ctc_cp_contact_id',
             'foreign' => 'cp_contact_id'));

        $this->hasOne('CpTypeAction', array(
             'local' => 'cp_action_ctc_cp_type_action_id',
             'foreign' => 'cp_type_action_id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'cp_action_ctc_user_id',
             'foreign' => 'id'));
    }
}