<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cab', 'dbrmv3');

/**
 * BaseCab
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cab_id
 * @property string $cab_driver
 * @property blob $cab_loc
 * 
 * @method integer getCabId()      Returns the current record's "cab_id" value
 * @method string  getCabDriver()  Returns the current record's "cab_driver" value
 * @method blob    getCabLoc()     Returns the current record's "cab_loc" value
 * @method Cab     setCabId()      Sets the current record's "cab_id" value
 * @method Cab     setCabDriver()  Sets the current record's "cab_driver" value
 * @method Cab     setCabLoc()     Sets the current record's "cab_loc" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCab extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cab');
        $this->hasColumn('cab_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cab_driver', 'string', 80, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('cab_loc', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}