<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpActionCv', 'dbcvp');

/**
 * BaseCpActionCv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cp_action_cv_id
 * @property string $cp_action_cv_detail
 * @property timestamp $cp_action_cv_date_creation
 * @property timestamp $cp_action_cv_date_modification
 * @property date $cp_action_cv_date_echeance
 * @property integer $cp_action_cv_cp_type_action_id
 * @property integer $cp_action_cv_covoitureur_id
 * @property integer $cp_action_cv_user_id
 * @property integer $cp_action_cv_trajet_id
 * @property CpTypeAction $CpTypeAction
 * @property sfGuardUser $User
 * @property Covoitureur $Covoitureur
 * @property Trajet $Trajet
 * 
 * @method integer      getCpActionCvId()                   Returns the current record's "cp_action_cv_id" value
 * @method string       getCpActionCvDetail()               Returns the current record's "cp_action_cv_detail" value
 * @method timestamp    getCpActionCvDateCreation()         Returns the current record's "cp_action_cv_date_creation" value
 * @method timestamp    getCpActionCvDateModification()     Returns the current record's "cp_action_cv_date_modification" value
 * @method date         getCpActionCvDateEcheance()         Returns the current record's "cp_action_cv_date_echeance" value
 * @method integer      getCpActionCvCpTypeActionId()       Returns the current record's "cp_action_cv_cp_type_action_id" value
 * @method integer      getCpActionCvCovoitureurId()        Returns the current record's "cp_action_cv_covoitureur_id" value
 * @method integer      getCpActionCvUserId()               Returns the current record's "cp_action_cv_user_id" value
 * @method integer      getCpActionCvTrajetId()             Returns the current record's "cp_action_cv_trajet_id" value
 * @method CpTypeAction getCpTypeAction()                   Returns the current record's "CpTypeAction" value
 * @method sfGuardUser  getUser()                           Returns the current record's "User" value
 * @method Covoitureur  getCovoitureur()                    Returns the current record's "Covoitureur" value
 * @method Trajet       getTrajet()                         Returns the current record's "Trajet" value
 * @method CpActionCv   setCpActionCvId()                   Sets the current record's "cp_action_cv_id" value
 * @method CpActionCv   setCpActionCvDetail()               Sets the current record's "cp_action_cv_detail" value
 * @method CpActionCv   setCpActionCvDateCreation()         Sets the current record's "cp_action_cv_date_creation" value
 * @method CpActionCv   setCpActionCvDateModification()     Sets the current record's "cp_action_cv_date_modification" value
 * @method CpActionCv   setCpActionCvDateEcheance()         Sets the current record's "cp_action_cv_date_echeance" value
 * @method CpActionCv   setCpActionCvCpTypeActionId()       Sets the current record's "cp_action_cv_cp_type_action_id" value
 * @method CpActionCv   setCpActionCvCovoitureurId()        Sets the current record's "cp_action_cv_covoitureur_id" value
 * @method CpActionCv   setCpActionCvUserId()               Sets the current record's "cp_action_cv_user_id" value
 * @method CpActionCv   setCpActionCvTrajetId()             Sets the current record's "cp_action_cv_trajet_id" value
 * @method CpActionCv   setCpTypeAction()                   Sets the current record's "CpTypeAction" value
 * @method CpActionCv   setUser()                           Sets the current record's "User" value
 * @method CpActionCv   setCovoitureur()                    Sets the current record's "Covoitureur" value
 * @method CpActionCv   setTrajet()                         Sets the current record's "Trajet" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpActionCv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cp_action_cv');
        $this->hasColumn('cp_action_cv_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_cv_detail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cp_action_cv_date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_cv_date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_cv_date_echeance', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp_action_cv_cp_type_action_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_cv_covoitureur_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_cv_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_action_cv_trajet_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CpTypeAction', array(
             'local' => 'cp_action_cv_cp_type_action_id',
             'foreign' => 'cp_type_action_id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'cp_action_cv_user_id',
             'foreign' => 'id'));

        $this->hasOne('Covoitureur', array(
             'local' => 'cp_action_cv_covoitureur_id',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('Trajet', array(
             'local' => 'cp_action_cv_trajet_id',
             'foreign' => 'id_trajet'));
    }
}