<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Covoitureur', 'dbrmv3');

/**
 * BaseCovoitureur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_utilisateur
 * @property string $cle
 * @property integer $etat
 * @property integer $etat_site_client_validation
 * @property timestamp $date_creation
 * @property timestamp $date_modification
 * @property timestamp $date_fin
 * @property integer $inscription_minute
 * @property string $identifiant
 * @property string $mot_de_passe
 * @property integer $sexe
 * @property integer $civilite
 * @property string $nom
 * @property string $prenom
 * @property string $adresse
 * @property integer $code_postal
 * @property string $ville
 * @property string $mail
 * @property string $mail_perso
 * @property string $telephone_mobile
 * @property string $telephone
 * @property integer $telephone_visible
 * @property string $telephone_autre
 * @property string $societe
 * @property string $matricule
 * @property string $service
 * @property string $tranche_age
 * @property date $date_naissance
 * @property integer $isMajeur
 * @property string $question
 * @property string $reponse
 * @property timestamp $date_derniere_connexion
 * @property integer $nombre_connexion
 * @property integer $permanente_connexion
 * @property integer $id_partenaire
 * @property integer $id_site_client
 * @property integer $id_site_site
 * @property integer $etat_photo
 * @property string $file_photo
 * @property string $photo_ext
 * @property integer $etat_video
 * @property integer $newsletter
 * @property integer $tolere_fumeur
 * @property integer $tolere_animaux
 * @property integer $tolere_bagage
 * @property integer $tolere_musique
 * @property integer $tolere_discussion
 * @property integer $note
 * @property string $dirgrp
 * @property string $dptag
 * @property string $svcpdv
 * @property integer $bascule
 * @property integer $id_facebook
 * @property integer $mise_en_relation_sms
 * @property integer $rsa
 * @property integer $id_covoitureur_lien_site
 * @property integer $id_covoitureur_fonction
 * @property integer $cp_etablissement_horaire_id
 * @property integer $cp_etablissement_secteur_id
 * @property integer $cp_etablissement_id
 * @property integer $id_csp
 * @property integer $lu_charte
 * @property integer $ss_mail
 * @property integer $ss_contact_covoit
 * @property integer $anonymat
 * @property integer $possede_vehicule
 * @property string $remarque
 * @property SiteClient $SiteClient
 * @property CovoitureurLienSite $CovoitureurLienSite
 * @property CovoitureurFonction $CovoitureurFonction
 * @property CpEtablissementHoraire $CpEtablissementHoraire
 * @property CpEtablissementSecteur $CpEtablissementSecteur
 * @property CpEtablissement $CpEtablissement
 * @property Csp $Csp
 * @property CovoitureurAmis $CovoitureurAmis
 * @property CovoitureurCentreInteret $CovoitureurCentreInteret
 * @property CovoitureurEquipages $CovoitureurEquipages
 * @property CovoitureurVehicule $CovoitureurVehicule
 * @property Equipage $Equipage
 * @property EquipageCovoitureur $EquipageCovoitureur
 * @property StatistiqueCovoitureur $StatistiqueCovoitureur
 * @property Trajet $Trajet
 * @property TrajetAlerte $TrajetAlerte
 * @property TrajetMiseEnRelation $TrajetMiseEnRelation
 * @property CpActionCv $CpActionCv
 * 
 * @method integer                  getIdUtilisateur()               Returns the current record's "id_utilisateur" value
 * @method string                   getCle()                         Returns the current record's "cle" value
 * @method integer                  getEtat()                        Returns the current record's "etat" value
 * @method integer                  getEtatSiteClientValidation()    Returns the current record's "etat_site_client_validation" value
 * @method timestamp                getDateCreation()                Returns the current record's "date_creation" value
 * @method timestamp                getDateModification()            Returns the current record's "date_modification" value
 * @method timestamp                getDateFin()                     Returns the current record's "date_fin" value
 * @method integer                  getInscriptionMinute()           Returns the current record's "inscription_minute" value
 * @method string                   getIdentifiant()                 Returns the current record's "identifiant" value
 * @method string                   getMotDePasse()                  Returns the current record's "mot_de_passe" value
 * @method integer                  getSexe()                        Returns the current record's "sexe" value
 * @method integer                  getCivilite()                    Returns the current record's "civilite" value
 * @method string                   getNom()                         Returns the current record's "nom" value
 * @method string                   getPrenom()                      Returns the current record's "prenom" value
 * @method string                   getAdresse()                     Returns the current record's "adresse" value
 * @method integer                  getCodePostal()                  Returns the current record's "code_postal" value
 * @method string                   getVille()                       Returns the current record's "ville" value
 * @method string                   getMail()                        Returns the current record's "mail" value
 * @method string                   getMailPerso()                   Returns the current record's "mail_perso" value
 * @method string                   getTelephoneMobile()             Returns the current record's "telephone_mobile" value
 * @method string                   getTelephone()                   Returns the current record's "telephone" value
 * @method integer                  getTelephoneVisible()            Returns the current record's "telephone_visible" value
 * @method string                   getTelephoneAutre()              Returns the current record's "telephone_autre" value
 * @method string                   getSociete()                     Returns the current record's "societe" value
 * @method string                   getMatricule()                   Returns the current record's "matricule" value
 * @method string                   getService()                     Returns the current record's "service" value
 * @method string                   getTrancheAge()                  Returns the current record's "tranche_age" value
 * @method date                     getDateNaissance()               Returns the current record's "date_naissance" value
 * @method integer                  getIsMajeur()                    Returns the current record's "isMajeur" value
 * @method string                   getQuestion()                    Returns the current record's "question" value
 * @method string                   getReponse()                     Returns the current record's "reponse" value
 * @method timestamp                getDateDerniereConnexion()       Returns the current record's "date_derniere_connexion" value
 * @method integer                  getNombreConnexion()             Returns the current record's "nombre_connexion" value
 * @method integer                  getPermanenteConnexion()         Returns the current record's "permanente_connexion" value
 * @method integer                  getIdPartenaire()                Returns the current record's "id_partenaire" value
 * @method integer                  getIdSiteClient()                Returns the current record's "id_site_client" value
 * @method integer                  getIdSiteSite()                  Returns the current record's "id_site_site" value
 * @method integer                  getEtatPhoto()                   Returns the current record's "etat_photo" value
 * @method string                   getFilePhoto()                   Returns the current record's "file_photo" value
 * @method string                   getPhotoExt()                    Returns the current record's "photo_ext" value
 * @method integer                  getEtatVideo()                   Returns the current record's "etat_video" value
 * @method integer                  getNewsletter()                  Returns the current record's "newsletter" value
 * @method integer                  getTolereFumeur()                Returns the current record's "tolere_fumeur" value
 * @method integer                  getTolereAnimaux()               Returns the current record's "tolere_animaux" value
 * @method integer                  getTolereBagage()                Returns the current record's "tolere_bagage" value
 * @method integer                  getTolereMusique()               Returns the current record's "tolere_musique" value
 * @method integer                  getTolereDiscussion()            Returns the current record's "tolere_discussion" value
 * @method integer                  getNote()                        Returns the current record's "note" value
 * @method string                   getDirgrp()                      Returns the current record's "dirgrp" value
 * @method string                   getDptag()                       Returns the current record's "dptag" value
 * @method string                   getSvcpdv()                      Returns the current record's "svcpdv" value
 * @method integer                  getBascule()                     Returns the current record's "bascule" value
 * @method integer                  getIdFacebook()                  Returns the current record's "id_facebook" value
 * @method integer                  getMiseEnRelationSms()           Returns the current record's "mise_en_relation_sms" value
 * @method integer                  getRsa()                         Returns the current record's "rsa" value
 * @method integer                  getIdCovoitureurLienSite()       Returns the current record's "id_covoitureur_lien_site" value
 * @method integer                  getIdCovoitureurFonction()       Returns the current record's "id_covoitureur_fonction" value
 * @method integer                  getCpEtablissementHoraireId()    Returns the current record's "cp_etablissement_horaire_id" value
 * @method integer                  getCpEtablissementSecteurId()    Returns the current record's "cp_etablissement_secteur_id" value
 * @method integer                  getCpEtablissementId()           Returns the current record's "cp_etablissement_id" value
 * @method integer                  getIdCsp()                       Returns the current record's "id_csp" value
 * @method integer                  getLuCharte()                    Returns the current record's "lu_charte" value
 * @method integer                  getSsMail()                      Returns the current record's "ss_mail" value
 * @method integer                  getSsContactCovoit()             Returns the current record's "ss_contact_covoit" value
 * @method integer                  getAnonymat()                    Returns the current record's "anonymat" value
 * @method integer                  getPossedeVehicule()             Returns the current record's "possede_vehicule" value
 * @method string                   getRemarque()                    Returns the current record's "remarque" value
 * @method SiteClient               getSiteClient()                  Returns the current record's "SiteClient" value
 * @method CovoitureurLienSite      getCovoitureurLienSite()         Returns the current record's "CovoitureurLienSite" value
 * @method CovoitureurFonction      getCovoitureurFonction()         Returns the current record's "CovoitureurFonction" value
 * @method CpEtablissementHoraire   getCpEtablissementHoraire()      Returns the current record's "CpEtablissementHoraire" value
 * @method CpEtablissementSecteur   getCpEtablissementSecteur()      Returns the current record's "CpEtablissementSecteur" value
 * @method CpEtablissement          getCpEtablissement()             Returns the current record's "CpEtablissement" value
 * @method Csp                      getCsp()                         Returns the current record's "Csp" value
 * @method CovoitureurAmis          getCovoitureurAmis()             Returns the current record's "CovoitureurAmis" value
 * @method CovoitureurCentreInteret getCovoitureurCentreInteret()    Returns the current record's "CovoitureurCentreInteret" value
 * @method CovoitureurEquipages     getCovoitureurEquipages()        Returns the current record's "CovoitureurEquipages" value
 * @method CovoitureurVehicule      getCovoitureurVehicule()         Returns the current record's "CovoitureurVehicule" value
 * @method Equipage                 getEquipage()                    Returns the current record's "Equipage" value
 * @method EquipageCovoitureur      getEquipageCovoitureur()         Returns the current record's "EquipageCovoitureur" value
 * @method StatistiqueCovoitureur   getStatistiqueCovoitureur()      Returns the current record's "StatistiqueCovoitureur" value
 * @method Trajet                   getTrajet()                      Returns the current record's "Trajet" value
 * @method TrajetAlerte             getTrajetAlerte()                Returns the current record's "TrajetAlerte" value
 * @method TrajetMiseEnRelation     getTrajetMiseEnRelation()        Returns the current record's "TrajetMiseEnRelation" value
 * @method CpActionCv               getCpActionCv()                  Returns the current record's "CpActionCv" value
 * @method Covoitureur              setIdUtilisateur()               Sets the current record's "id_utilisateur" value
 * @method Covoitureur              setCle()                         Sets the current record's "cle" value
 * @method Covoitureur              setEtat()                        Sets the current record's "etat" value
 * @method Covoitureur              setEtatSiteClientValidation()    Sets the current record's "etat_site_client_validation" value
 * @method Covoitureur              setDateCreation()                Sets the current record's "date_creation" value
 * @method Covoitureur              setDateModification()            Sets the current record's "date_modification" value
 * @method Covoitureur              setDateFin()                     Sets the current record's "date_fin" value
 * @method Covoitureur              setInscriptionMinute()           Sets the current record's "inscription_minute" value
 * @method Covoitureur              setIdentifiant()                 Sets the current record's "identifiant" value
 * @method Covoitureur              setMotDePasse()                  Sets the current record's "mot_de_passe" value
 * @method Covoitureur              setSexe()                        Sets the current record's "sexe" value
 * @method Covoitureur              setCivilite()                    Sets the current record's "civilite" value
 * @method Covoitureur              setNom()                         Sets the current record's "nom" value
 * @method Covoitureur              setPrenom()                      Sets the current record's "prenom" value
 * @method Covoitureur              setAdresse()                     Sets the current record's "adresse" value
 * @method Covoitureur              setCodePostal()                  Sets the current record's "code_postal" value
 * @method Covoitureur              setVille()                       Sets the current record's "ville" value
 * @method Covoitureur              setMail()                        Sets the current record's "mail" value
 * @method Covoitureur              setMailPerso()                   Sets the current record's "mail_perso" value
 * @method Covoitureur              setTelephoneMobile()             Sets the current record's "telephone_mobile" value
 * @method Covoitureur              setTelephone()                   Sets the current record's "telephone" value
 * @method Covoitureur              setTelephoneVisible()            Sets the current record's "telephone_visible" value
 * @method Covoitureur              setTelephoneAutre()              Sets the current record's "telephone_autre" value
 * @method Covoitureur              setSociete()                     Sets the current record's "societe" value
 * @method Covoitureur              setMatricule()                   Sets the current record's "matricule" value
 * @method Covoitureur              setService()                     Sets the current record's "service" value
 * @method Covoitureur              setTrancheAge()                  Sets the current record's "tranche_age" value
 * @method Covoitureur              setDateNaissance()               Sets the current record's "date_naissance" value
 * @method Covoitureur              setIsMajeur()                    Sets the current record's "isMajeur" value
 * @method Covoitureur              setQuestion()                    Sets the current record's "question" value
 * @method Covoitureur              setReponse()                     Sets the current record's "reponse" value
 * @method Covoitureur              setDateDerniereConnexion()       Sets the current record's "date_derniere_connexion" value
 * @method Covoitureur              setNombreConnexion()             Sets the current record's "nombre_connexion" value
 * @method Covoitureur              setPermanenteConnexion()         Sets the current record's "permanente_connexion" value
 * @method Covoitureur              setIdPartenaire()                Sets the current record's "id_partenaire" value
 * @method Covoitureur              setIdSiteClient()                Sets the current record's "id_site_client" value
 * @method Covoitureur              setIdSiteSite()                  Sets the current record's "id_site_site" value
 * @method Covoitureur              setEtatPhoto()                   Sets the current record's "etat_photo" value
 * @method Covoitureur              setFilePhoto()                   Sets the current record's "file_photo" value
 * @method Covoitureur              setPhotoExt()                    Sets the current record's "photo_ext" value
 * @method Covoitureur              setEtatVideo()                   Sets the current record's "etat_video" value
 * @method Covoitureur              setNewsletter()                  Sets the current record's "newsletter" value
 * @method Covoitureur              setTolereFumeur()                Sets the current record's "tolere_fumeur" value
 * @method Covoitureur              setTolereAnimaux()               Sets the current record's "tolere_animaux" value
 * @method Covoitureur              setTolereBagage()                Sets the current record's "tolere_bagage" value
 * @method Covoitureur              setTolereMusique()               Sets the current record's "tolere_musique" value
 * @method Covoitureur              setTolereDiscussion()            Sets the current record's "tolere_discussion" value
 * @method Covoitureur              setNote()                        Sets the current record's "note" value
 * @method Covoitureur              setDirgrp()                      Sets the current record's "dirgrp" value
 * @method Covoitureur              setDptag()                       Sets the current record's "dptag" value
 * @method Covoitureur              setSvcpdv()                      Sets the current record's "svcpdv" value
 * @method Covoitureur              setBascule()                     Sets the current record's "bascule" value
 * @method Covoitureur              setIdFacebook()                  Sets the current record's "id_facebook" value
 * @method Covoitureur              setMiseEnRelationSms()           Sets the current record's "mise_en_relation_sms" value
 * @method Covoitureur              setRsa()                         Sets the current record's "rsa" value
 * @method Covoitureur              setIdCovoitureurLienSite()       Sets the current record's "id_covoitureur_lien_site" value
 * @method Covoitureur              setIdCovoitureurFonction()       Sets the current record's "id_covoitureur_fonction" value
 * @method Covoitureur              setCpEtablissementHoraireId()    Sets the current record's "cp_etablissement_horaire_id" value
 * @method Covoitureur              setCpEtablissementSecteurId()    Sets the current record's "cp_etablissement_secteur_id" value
 * @method Covoitureur              setCpEtablissementId()           Sets the current record's "cp_etablissement_id" value
 * @method Covoitureur              setIdCsp()                       Sets the current record's "id_csp" value
 * @method Covoitureur              setLuCharte()                    Sets the current record's "lu_charte" value
 * @method Covoitureur              setSsMail()                      Sets the current record's "ss_mail" value
 * @method Covoitureur              setSsContactCovoit()             Sets the current record's "ss_contact_covoit" value
 * @method Covoitureur              setAnonymat()                    Sets the current record's "anonymat" value
 * @method Covoitureur              setPossedeVehicule()             Sets the current record's "possede_vehicule" value
 * @method Covoitureur              setRemarque()                    Sets the current record's "remarque" value
 * @method Covoitureur              setSiteClient()                  Sets the current record's "SiteClient" value
 * @method Covoitureur              setCovoitureurLienSite()         Sets the current record's "CovoitureurLienSite" value
 * @method Covoitureur              setCovoitureurFonction()         Sets the current record's "CovoitureurFonction" value
 * @method Covoitureur              setCpEtablissementHoraire()      Sets the current record's "CpEtablissementHoraire" value
 * @method Covoitureur              setCpEtablissementSecteur()      Sets the current record's "CpEtablissementSecteur" value
 * @method Covoitureur              setCpEtablissement()             Sets the current record's "CpEtablissement" value
 * @method Covoitureur              setCsp()                         Sets the current record's "Csp" value
 * @method Covoitureur              setCovoitureurAmis()             Sets the current record's "CovoitureurAmis" value
 * @method Covoitureur              setCovoitureurCentreInteret()    Sets the current record's "CovoitureurCentreInteret" value
 * @method Covoitureur              setCovoitureurEquipages()        Sets the current record's "CovoitureurEquipages" value
 * @method Covoitureur              setCovoitureurVehicule()         Sets the current record's "CovoitureurVehicule" value
 * @method Covoitureur              setEquipage()                    Sets the current record's "Equipage" value
 * @method Covoitureur              setEquipageCovoitureur()         Sets the current record's "EquipageCovoitureur" value
 * @method Covoitureur              setStatistiqueCovoitureur()      Sets the current record's "StatistiqueCovoitureur" value
 * @method Covoitureur              setTrajet()                      Sets the current record's "Trajet" value
 * @method Covoitureur              setTrajetAlerte()                Sets the current record's "TrajetAlerte" value
 * @method Covoitureur              setTrajetMiseEnRelation()        Sets the current record's "TrajetMiseEnRelation" value
 * @method Covoitureur              setCpActionCv()                  Sets the current record's "CpActionCv" value
 * 
 * @package    roulezmailn_v3
 * @subpackage model
 * @author     RoulezMalin <technique@roulezmalin.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCovoitureur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('covoitureur');
        $this->hasColumn('id_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('etat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('etat_site_client_validation', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_creation', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_modification', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('inscription_minute', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('identifiant', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('mot_de_passe', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('sexe', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('civilite', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('prenom', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('adresse', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('code_postal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ville', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mail_perso', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('telephone_mobile', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('telephone', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('telephone_visible', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('telephone_autre', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('societe', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('matricule', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('service', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('tranche_age', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('date_naissance', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('isMajeur', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('question', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('reponse', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('date_derniere_connexion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nombre_connexion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('permanente_connexion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_partenaire', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_site_client', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_site_site', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('etat_photo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('file_photo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('photo_ext', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('etat_video', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('newsletter', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tolere_fumeur', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tolere_animaux', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tolere_bagage', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('tolere_musique', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tolere_discussion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('note', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '5',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('dirgrp', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dptag', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('svcpdv', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bascule', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_facebook', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mise_en_relation_sms', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rsa', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_covoitureur_lien_site', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_covoitureur_fonction', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_etablissement_horaire_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_etablissement_secteur_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cp_etablissement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_csp', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lu_charte', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ss_mail', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ss_contact_covoit', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('anonymat', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('possede_vehicule', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('remarque', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteClient', array(
             'local' => 'id_site_site',
             'foreign' => 'id_site_client'));

        $this->hasOne('CovoitureurLienSite', array(
             'local' => 'id_covoitureur_lien_site',
             'foreign' => 'id_covoitureur_lien_site'));

        $this->hasOne('CovoitureurFonction', array(
             'local' => 'id_covoitureur_fonction',
             'foreign' => 'id_covoitureur_fonction'));

        $this->hasOne('CpEtablissementHoraire', array(
             'local' => 'cp_etablissement_horaire_id',
             'foreign' => 'cp_etablissement_horaire_id'));

        $this->hasOne('CpEtablissementSecteur', array(
             'local' => 'cp_etablissement_secteur_id',
             'foreign' => 'cp_etablissement_secteur_id'));

        $this->hasOne('CpEtablissement', array(
             'local' => 'cp_etablissement_id',
             'foreign' => 'cp_etablissement_id'));

        $this->hasOne('Csp', array(
             'local' => 'id_csp',
             'foreign' => 'id_csp'));

        $this->hasOne('CovoitureurAmis', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_covoitureur_amis'));

        $this->hasOne('CovoitureurCentreInteret', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('CovoitureurEquipages', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateurb'));

        $this->hasOne('CovoitureurVehicule', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('Equipage', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_createur'));

        $this->hasOne('EquipageCovoitureur', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_covoitureur'));

        $this->hasOne('StatistiqueCovoitureur', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_covoitureur'));

        $this->hasOne('Trajet', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('TrajetAlerte', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('TrajetMiseEnRelation', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_demandeur'));

        $this->hasOne('CpActionCv', array(
             'local' => 'id_utilisateur',
             'foreign' => 'cp_action_cv_covoitureur_id'));
    }
}